### ISSUE TITLE
signature of Arch Linux repository broken (subtitlecomposer.db.sig is a HTML file).

### ISSUE THREAD

**Issue by felixbecker2** [maxrd2/subtitlecomposer#100]
You maintain the compiled packages of this repository as an Arch Linux repository, as mentioned
under
http://wiki.archlinux.org/index.php/unofficial_user_repositories#subtitlecomposer.

It is mentioned that it is a signed repository.

However, it is no longer possible to retrieve the signature:

http://smoothware.net/subtitlecomposer/x86_64/subtitlecomposer.db.sig
is a HTML file.

So, the signature cannot be imported.

Snippet from `pacman -Sy`:

    === Downloading 'http://smoothware.net/subtitlecomposer/x86_64/subtitlecomposer.db' to '/var/lib/pacman/sync/subtitlecomposer.db.part' ... ===
    
    --2018-02-26 11:12:25--  http://smoothware.net/subtitlecomposer/x86_64/subtitlecomposer.db
    Resolving smoothware.net (smoothware.net)... 91.195.240.82
    Connecting to smoothware.net (smoothware.net)|91.195.240.82|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: unspecified [text/html]
    Saving to: ‘/var/lib/pacman/sync/subtitlecomposer.db.part’
    
    /var/lib/pacman/sync/subtitlecomposer.db.part            [ <=>                                                                                                                   ]  19.78K  --.-KB/s    in 0.06s   
    
    2018-02-26 11:12:25 (326 KB/s) - ‘/var/lib/pacman/sync/subtitlecomposer.db.part’ saved [20257]
    
    
    === Downloading 'http://smoothware.net/subtitlecomposer/x86_64/subtitlecomposer.db.sig' to '/var/lib/pacman/sync/subtitlecomposer.db.sig.part' ... ===
    
    --2018-02-26 11:12:25--  http://smoothware.net/subtitlecomposer/x86_64/subtitlecomposer.db.sig
    Resolving smoothware.net (smoothware.net)... 91.195.240.82
    Connecting to smoothware.net (smoothware.net)|91.195.240.82|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: unspecified [text/html]
    Saving to: ‘/var/lib/pacman/sync/subtitlecomposer.db.sig.part’
    
    /var/lib/pacman/sync/subtitlecomposer.db.sig.part        [ <=>                                                                                                                   ]  19.79K  --.-KB/s    in 0.1s    
    
    2018-02-26 11:12:26 (144 KB/s) - ‘/var/lib/pacman/sync/subtitlecomposer.db.sig.part’ saved [20261]
    
    error: GPGME error: No data
    error: subtitlecomposer: missing required signature
    error: failed to update subtitlecomposer (invalid or corrupted database (PGP signature))

**Comment by maxrd2** [comment]
thanks, have fixed it some time ago
