### ISSUE TITLE
Make error checking usable, add ability to automatically fix errors.

### ISSUE THREAD

**Issue by maxrd2** [maxrd2/SubtitleComposer#106]
- Reuse whitespace correction code and english ocr correction code from vobsub import
- Place regexps to external files that can be easily enabled/disabled from in-app dialog
- Change "Error Menu" to contain:
  - Detect Errors... - search for errors through lines and flag them (using above regexps)
  - Fix Errors... - search for errors through lines and fix them (using above regexps)
  - Clear Errors - clear error flags from lines
  - Jump to Next/Prev error - jump to next/prev flagged error
  - Toggle Mark
  - Jump to Next/Prev mark
  - Clear Mark
- Remove/improve relevant entries from Texts menu

**Comment by duck7000** [comment]
Just a question, are you going to work on this?
The fix errors got my attention, this is at the moment not possible afaik

**Comment by maxrd2** [comment]
Yes... have already started some work.

**Comment by maxrd2** [comment]
Issue was moved here: https://invent.kde.org/kde/subtitlecomposer/issues/9
