### ISSUE TITLE
Waveform is out of sync

### ISSUE THREAD

**Issue by Gitraffe** [maxrd2/subtitlecomposer#108]
Audio starts ~100-200ms before waveform. This happened with all files I tried.

**Comment by maxrd2** [comment]
Which video player backend are you using?
I'm pretty sure this is not the problem with the waveform. Maybe player backend uses ~100-200ms buffer or something like that.
If that's the case i might add a correction in each player backend to delay audio/video by some amount.
I've had the same **feeling** sometimes, but after syncing subtitles to waveform visually, saving them and playing video w/ titles in some external player (PC, TV, ...) it would be synced perfectly.

**Comment by Gitraffe** [comment]
Tried with Gstreamer and MPV player. With other players, can't open mkv files.

**Comment by maxrd2** [comment]
Have tried to reproduce this a bit more again, on normal 1x playing speed and 0.2x. Player backends signal their play position roughly every 50-60ms. If there is inaccuracy it's less than ~30ms, and I'm not sure that there is. Speech in a phrase usually doesn't start with full amplitude, so it may seem like audio is drawn later on the waveform.
I suppose you are using pulseaudio or some kind of sound server, are you sure there aren't any delays there, maybe there is something strange in their configuration?
Do you have an idea how to measure this exactly and accurately?

**Comment by duck7000** [comment]
Now that this is mentioned i got the same feeling sometimes.
It feels like if the waveform is late. The speaking is slightly sooner as the waveform.

Like you said maxrd2 it doesn't feel like a real problem, but if you pay attention you notice it 

I use the default player backend (gstreamer) on a standard Linuxmint cinnamon 18.3

**Comment by maxrd2** [comment]
The audio in containers sometimes doesn't start when video starts. And some frames might be offset from expect play position. Have changed the code to draw waveform using those timestamps.
@Gitraffe Could you please `checkout fix-waveform-times` branch and check if that fixed it.

**Comment by maxrd2** [comment]
There is an working AppImage now too here: https://github.com/maxrd2/subtitlecomposer/releases
It has this change applied, so you can try that one without rebuilding everything.
