### ISSUE TITLE
Add crash recovery, auto save timer option.

### ISSUE THREAD

**Issue by maxrd2** [maxrd2/SubtitleComposer#113]
Add feature to save undo history to temp file. Once app closes this file is deleted. If app/system crashes and file stays on disk, on next start app will notice the file and prompt user to recover. Whole state and undo history would be restored.

Add an option to perform auto saving every N minutes. It can be setup to:
- disabled
- save to .bak extension
- overwrite original file

**Comment by duck7000** [comment]
Very usefull, although it never happened to me, but i have the tendency to use ctrl s frequently

**Comment by codesearcher** [comment]
Recently, my computer turns off by lack of eletricity.
I've lost almost an hour of work. If this feature was enabled... this could be avoided.

**Comment by maxrd2** [comment]
Issue was moved here: https://invent.kde.org/kde/subtitlecomposer/issues/8
