### ISSUE TITLE
Failed to build on Ubuntu 18.04.1, 18.10, 19.04

### ISSUE THREAD

**Issue by muzena** [maxrd2/SubtitleComposer#116]
I don't know why build Failed when i add to control file build dependencies for speech recognition:  libsphinxbase3, libsphinxbase-dev, libpocketsphinx3, libpocketsphinx-dev
Build log: https://launchpadlibrarian.net/398904855/buildlog_ubuntu-bionic-amd64.subtitlecomposer_0.6.6-2-201811241901~ubuntu18.04.1_BUILDING.txt.gz

**Comment by maxrd2** [comment]
Your sphinxbase/pocketsphinx version is too old.
There was a same problem here https://github.com/maxrd2/subtitlecomposer/issues/70#issuecomment-287586854

**Comment by muzena** [comment]
@duck7000 
I fix this, add  sphinxbase, pocketsphinx builds to PPA repo.
https://code.launchpad.net/~trebelnik-stefina/+archive/ubuntu/subtitlecomposer?field.series_filter=
@maxrd2 
Can I register Subtitlecomposer project and team in Launchpad to auto import git code and auto build deps in PPA?
Like this:
https://launchpad.net/nightingale
https://launchpad.net/~nightingaleteam 
https://launchpad.net/~nightingaleteam/+archive/ubuntu/nightingale-nightly

**Comment by maxrd2** [comment]
@muzena sure you can.. that would be great
You will have to build pocketsphinx and sphinxbase, don't think ubuntu is shipping too recent version yet.

**Comment by muzena** [comment]
@maxrd2 
Auto import from github and auto build PPA for Subtitlecomposer, pocketsphinx and sphinxbase:
https://code.launchpad.net/~subtitlecomposer/+archive/ubuntu/subtitlecomposer-git

**Comment by muzena** [comment]
Is there exist a way to extract this tipe of subtitles from video, this is DVB-t from TV record?
https://drive.google.com/open?id=1zpBHs0WWbSD9f03V7aRLArqWJr7QJhXC

**Comment by Martchus** [comment]
@muzena That would require an OCR engine since the subtitles are burned in.

**Comment by duck7000** [comment]
@muzena 
Thanks for the subtitlecomposer-git PPA!

**Comment by duck7000** [comment]
Is it possible to add this https://code.launchpad.net/~subtitlecomposer/+archive/ubuntu/subtitlecomposer-git
to the releases page? There everybody can find it easily

**Comment by muzena** [comment]
@duck7000 
https://github.com/maxrd2/subtitlecomposer/pull/122
