### ISSUE TITLE
undefined symbol:  xcb_dri3_get_supported_modifiers

### ISSUE THREAD

**Issue by probonopd** [maxrd2/subtitlecomposer#117]
```
usr/bin/subtitlecomposer: symbol lookup error: /usr/lib64/libGL.so.1: undefined symbol: 
xcb_dri3_get_supported_modifiers
```

Solution: Please do __not__ bundle

-  'libxcb-dri3.so.0'
-  'libxcb-dri2.so.0'

References:
* https://github.com/AppImage/appimage.github.io/pull/964
* https://github.com/probonopd/linuxdeployqt/issues/331

**Comment by maxrd2** [comment]
Thank you for reporting and help. Will close this now.

**Comment by jlarevaloh** [comment]
Hello, just to share my experience with Eagle installation (eagle-9.4.2) on Ubuntu (18.04.1-Ubuntu).
I got same error: "./eagle: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers"
Then I removed this library from my Eagle installation package:
/Downloads/eagle-9.4.2/lib$ rm libxcb-dri3.so.0
and it work fine!, 
/Downloads/eagle-9.4.2$ ./eagle run
Hope this help you!
