### ISSUE TITLE
Unable to edit scripts in Appimage

### ISSUE THREAD

**Issue by malnaanah** [maxrd2/subtitlecomposer#118]
I am using the Appimage for V 0.7.0 in Kubuntu 18.04. 

When I run script manager and try to edit any script, an option to choose an application appears, but it is empty. If I write kate manually, it does not run and I can't edit the scripts.

**Comment by maxrd2** [comment]
Thanks for the report. This should be fixed now.

**Comment by maxrd2** [comment]
Will close this one now. Please reopen if you still have problems.
