### ISSUE TITLE
invalid 8-bit characters outside valid multi-byte UTF-8 sequences mkvtoolnix error

### ISSUE THREAD

**Issue by duck7000** [maxrd2/subtitlecomposer#119]
I get this error sometimes in mkvtoolnix:
This text subtitle track contains invalid 8-bit characters outside valid multi-byte UTF-8 sequences. Please specify the correct encoding for this track.

So my question is can i check in subtitlecomposer for this kind of error? if so, how do i do that?

If not, can this be added to the error checks?

**Comment by maxrd2** [comment]
It looks like utf8 encoding problem. Opening that subtitle and saving it with SC should create valid utf8 encoding. Is subtitle embedded mkv stream or external file? If it's embedded you can only import it and save it as external file with SC.

**Comment by duck7000** [comment]
Yes it looks to me also a utf8 problem, and it is saved with SC..

It is a external srt subtitle .

In settings it is set to utf8 but in the save as window it says iso-8859-1 . maybe that is where the problem is?
After editing i use ctrl-s to save it, so how does SC save the file?

**Comment by maxrd2** [comment]
Ctrl+S saves it with same encoding it was loaded with or previously saveAs-ed with.
If you save as utf8 it will create valid utf8 text.

**Comment by duck7000** [comment]
Aah now i get it.
So if the opened subtitle isn't uft8,  ctrl-s saves it as is!
I always assumed that no matter what is loaded it will be saved, according to the settings, as utf8, Apparently this is not the case

So for future use it is better to save as utf8 if i don't no up front if the subtitle already is utf8

Thanks for the explaining!
