### ISSUE TITLE
Toggle Waveform window?

### ISSUE THREAD

**Issue by jimbolaya** [maxrd2/subtitlecomposer#120]
I'm using Version 0.6.6 on Bionic using the package.

The waveform window is really cool and I'll likely use it when I have screen space. One of the screens I use is pretty small and I was hoping to find a way to toggle the window off so I don't see it. 

I saw nothing obvious on how to do that. Is this something I can do? Do I need a newer version?

**Comment by maxrd2** [comment]
It can be hidden by right clicking waveform titlebar, but that feature was introduced after 0.6.6 (commit https://github.com/maxrd2/subtitlecomposer/commit/32fe5f80ab604b1c21bc4d8b71dbfa1b307c96a4).
You can get latest AppImage release here: https://github.com/maxrd2/subtitlecomposer/releases
