### ISSUE TITLE
Speech Recognition failed

### ISSUE THREAD

**Issue by bluelavalamp** [maxrd2/subtitlecomposer#121]
I just downloaded the appimage (version 0.7.0) and I loaded a video and subtitles file.  From there I did Video->Recognize Speech and I get a window popup that says:

"Speech Recognition failed: Initialization of speech recognition plugin failed
Code 1: "

Any suggestions on how to fix this?

Thanks

**Comment by duck7000** [comment]
I don't know exactly how appimages work but in general you need this dependecies to get it working:

I have these dependencies installed for speech recognition:
gstreamer1.0-pocketsphinx
libpocketsphinx-dev
libpocketsphinx3
libsphinxbase-dev
libsphinxbase3
pocketsphinx
pocketsphinx-en-us
python-pocketsphinx
python-sphinxbase
sphinxbase-utils
swig-sphinxbase

@maxrd2 
It should be included in the appimage i believe?

**Comment by maxrd2** [comment]
@bluelavalamp I have added pocketsphinx configuration page to application.
Acoustic and language models are not included in appimage as there can be multiple for each language and they are usually pretty big.
You should download desired Model from https://cmusphinx.github.io/wiki/download/ and then setup paths in SubtitileComposer > Settings > Configure > PocketSphinx
