### ISSUE TITLE
How do I close the waveform (or video)?

### ISSUE THREAD

**Issue by gri1n** [maxrd2/subtitlecomposer#125]
I'd like to close the waveform when I don't need it but I can't find how. I've noticed there is a checkbox when you right click on certain parts of the UI but both the waveform and video checkboxes are greyed out.

![sc-screenshot](https://user-images.githubusercontent.com/5396580/56856993-877d3f80-69aa-11e9-8865-c19af8ed9b00.png)

**Comment by maxrd2** [comment]
It's been fixed in 32fe5f80ab604b1c21bc4d8b71dbfa1b307c96a4
