### ISSUE TITLE
BUG Subtitlecomposer can't open files whose name contain '#'

### ISSUE THREAD

**Issue by damodamo29** [maxrd2/subtitlecomposer#127]
Hi,
I noticed that no subtitle file whose name or path contain '#' can be open.
example:
/my path to subtitles/subtitle #1.srt
/my path to subtitles #1/subtitle.srt

It triggers a 'Sorry' dialog box:
'Could not parse the subtitle file'
'This may have been caused by usage of the wrong encoding'

OS Ubuntu 18.04
Thanks

**Comment by maxrd2** [comment]
Works fine here. Are you using the latest version?

**Comment by duck7000** [comment]
I can confirm that this issue also exists on Linux Mint 19.1, With the latest git version.

It is not a issue for me because i never use '#' in a filename

**Comment by maxrd2** [comment]
I was trying opening relative path containing #... that worked. Absolute paths should be good now too.
Thanks for the report.
