### ISSUE TITLE
PGS support

### ISSUE THREAD

**Issue by rschouwenburg** [maxrd2/subtitlecomposer#129]
Is it possible to add PGS / .sup support?

It kind of works already when you rename the .sup to .idx. The only problem is that the start time of every line is doubled. Now you can simply readjust that, but it gets old quickly when doing TV shows. :)

**Comment by maxrd2** [comment]
Yes.. any idea where I can get a sample PGS file?
Have tried googling both found nothing useful.

**Comment by rschouwenburg** [comment]
Here's an example. The PGS subtitles come in a SUP container.

https://www.dropbox.com/s/rraj0kmp32snzty/s01e01-2.sup?dl=0

Let me know when you have it so I can disable the share.

**Comment by maxrd2** [comment]
> The only problem is that the start time of every line is doubled.

What do you mean by this?
Have tried opening subtitles from .m2ts file, and it OCR works as it's supposed to.
So it works already, I just have to add .m2ts and .sup extensions to open dialog.

**Comment by rschouwenburg** [comment]
> > The only problem is that the start time of every line is doubled.
> 
> What do you mean by this?

Yea I could have made that more clear.

To get proper sync, I need to shift all the lines with half the start time of the first line. For example, if the start time of the first line is 00:02:40.000, I shift ALL lines backwards by 00:01:20.000.

I verified this with SubtitleEdit which natively supports SUP files, but is not as user-friendly and mature as Subtitle Composer IMHO.

**Comment by rschouwenburg** [comment]
I can share a proper SRT of the SUP I shared earlier if you want. Let me know.

**Comment by maxrd2** [comment]
> I can share a proper SRT of the SUP I shared earlier if you want. Let me know.

Have downloaded s01e01-2.sup... After doing "manual OCR" I got this:
![image](https://user-images.githubusercontent.com/1187381/59366063-f08dfc00-8d39-11e9-9fe5-6491db78fd6c.png)

If your timings are different this is most likely a bug in ffmpeg which is used to extract subtitle images.
Are my times accurate?
What ffmpeg version are you using?

**Comment by rschouwenburg** [comment]
Your timings in the screenshot are correct. This is what I am seeing when OCR-ing the same file:

![Screenshot from 2019-06-12 11-50-26](https://user-images.githubusercontent.com/17439419/59366518-6c6f5080-8d08-11e9-87f4-f9c91ac4167d.png)

I do not have ffmpeg on my system. I am on Linux Mint 19.1 (Ubuntu 18.04) and using v0.6.6 from the default repository.

**Comment by maxrd2** [comment]
OCR uses ffmpeg - it wouldn't work without it. 

Executing following will show locations of ffmpegs's libav libraries:
```bash
$ ldd /usr/bin/subtitlecomposer | grep libav
        libavcodec.so.58 => /usr/lib/libavcodec.so.58 (0x00007fbf85b78000)
        libavformat.so.58 => /usr/lib/libavformat.so.58 (0x00007fbf85923000)
        libavutil.so.56 => /usr/lib/libavutil.so.56 (0x00007fbf858a6000)
```
Then you should be able to execute something like this to figure which package provides those libraries:
```bash
apt-file find /usr/lib/libavcodec.so.58
```

**Comment by rschouwenburg** [comment]
Here you go:
```
$ ldd /usr/bin/subtitlecomposer | grep libav
	libavcodec.so.57 => /usr/lib/x86_64-linux-gnu/libavcodec.so.57 (0x00007ff5ec479000)
	libavformat.so.57 => /usr/lib/x86_64-linux-gnu/libavformat.so.57 (0x00007ff5ec021000)
	libavutil.so.55 => /usr/lib/x86_64-linux-gnu/libavutil.so.55 (0x00007ff5ebd95000)

$ apt-file find /usr/lib/x86_64-linux-gnu/libavcodec.so.57
libavcodec-extra57: /usr/lib/x86_64-linux-gnu/libavcodec.so.57
libavcodec-extra57: /usr/lib/x86_64-linux-gnu/libavcodec.so.57.107.100
libavcodec57: /usr/lib/x86_64-linux-gnu/libavcodec.so.57
libavcodec57: /usr/lib/x86_64-linux-gnu/libavcodec.so.57.107.100

```

**Comment by maxrd2** [comment]
Please use latest AppImage from here: https://github.com/maxrd2/subtitlecomposer/releases ... it works fine here.
The ffmpeg version on your system is providing bad timestamps to subtitle composer. Maybe you can file the bug report to packager (v0.6.6 from the default repository) so they can update the ffmpeg.

**Comment by rschouwenburg** [comment]
Yes, good idea. I'll file a bug report.

It would be great if you could consider making available a flatpak on flathub.

Thanks for your help!

**Comment by maxrd2** [comment]
You can open .sup files now without renaming them.
Will close this one now. Thank you for report!

**Comment by muzena** [comment]
@rschouwenburg 
You can try now PPA I add FFMPEG 4 to PPA.

**Comment by rschouwenburg** [comment]
@muzena works like a charm. Can you also include the scripts in the package? I use the "remove-hearing-impaired-text.js" a lot. It is include in the AppImage.

**Comment by muzena** [comment]
@rschouwenburg @maxrd2 
I don't now why scripts is missing in new builds? :(
