### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by duck7000** [maxrd2/SubtitleComposer#130]
Hi @maxrd2 

First of all i want to thank you for all your work to make this excellent subtitle editor!

Did you think/consider to accept donations?
if so where/how can i do so?

**Comment by maxrd2** [comment]
Very kind words... really appreciate it. Working and contributing to a project like this and seeing people using and liking it is great satisfaction and motivation for me. So.. thank you @duck7000 !

Also want to thank everyone who contributed with code, ideas, suggestions, took time to file a bug report or have just spread the word.

I haven't considered donations until now. Am not even sure how I would set it up properly. I should probably make an account on PayPal and a page with form and list of donations.

**Comment by duck7000** [comment]
If you set it up i'm sure people will donate.
I will for sure.

If i found a bug or problem i always open a issue here for several reasons.
First it is known to you but also to other users.
If it gets fixed everybody can benefit from it, not just me.

Not only this program but i do that for other github programs, like imdbphp2 and alwaysClear (a chrome extension) that i use a lot

**Comment by maxrd2** [comment]
Have finally set up a [ko-fi](https://ko-fi.com/maxrd2) and a [paypal](https://www.paypal.me/maxrd2) page.
Cheers

**Comment by duck7000** [comment]
Thanks for setting it up, my donation is already done!

**Comment by duck7000** [comment]
Maybe the donation can be added to the readme on the first page of this github account?
Everybody will notice it there, and maybe donate
