### ISSUE TITLE
Save waveform

### ISSUE THREAD

**Issue by duck7000** [maxrd2/SubtitleComposer#137]
Is it possible to save the generated waveform?

This would be handy if you work on the same subtitle multiple times.
Now every time i open the subtitle the waveform has to be generated again.

**Comment by maxrd2** [comment]
Yes... it's already on to-do list among other things.

**Comment by maxrd2** [comment]
Issue was moved here: https://invent.kde.org/kde/subtitlecomposer/issues/7
