### ISSUE TITLE
PPA build

### ISSUE THREAD

**Issue by muzena** [maxrd2/SubtitleComposer#138]
@maxrd2 
Can you change when you released Subtitlecomposer also version in
/pkg/debian-old/changelog
/pkg/debian/changelog
eg. for this release
subtitlecomposer (0.6.6-2) unstable; urgency=emergency
to
subtitlecomposer (0.7.0-0) unstable; urgency=emergency
to start auto build new version so I can delete my github fork and duplicate repo on launchpad

**Comment by maxrd2** [comment]
Will do a script at some point that will update versions and build instructions in all build packages that are supported right before release. Going from 0.6.6 to 0.7.0 need more than a version change there i believe.
Please look at arch PKGBUILD here: https://github.com/maxrd2/SubtitleComposer/blob/master/pkg/arch/PKGBUILD-git pkver() and build() functions. Git commit id is included in application version and some cmake params changed.

**Comment by muzena** [comment]
@maxrd2 
Is new FFMPEG needed only for building or as a install dependencies also?
Can you please change versions, it shows wrong version in PPA:
https://launchpad.net/~subtitlecomposer/+archive/ubuntu/subtitlecomposer-git
https://launchpad.net/~subtitlecomposer/+archive/ubuntu/subtitlecomposer-git-stable

**Comment by maxrd2** [comment]
Both I believe.

**Comment by maxrd2** [comment]
@muzena have cleaned up launchpad, renamed, deleted and moved things around so it's more obvious.
Have also dropped builds for trusty and xenial, I don't see point of those - to build them properly a lot of dependencies should be built. People on old distros can just use and download AppImage.

Is there an easy way to change url of https://launchpad.net/~subtitlecomposer/+archive/ubuntu/subtitlecomposer-git-stable to .../subtitlecomposer ?

Stable version is now using same version scheme as official packages and does not and should not have git in package version.

**Comment by muzena** [comment]
@maxrd2 
No, you can only add on project page few preordered pages [(homepage, wiki...)](https://launchpad.net/subtitlecomposer/+edit)
