### ISSUE TITLE
Support: not getting any meaningful menu/UI

### ISSUE THREAD

**Issue by gcb** [maxrd2/SubtitleComposer#139]
I am trying to build using Phonon under a Arch/KDE environment.

I do not see any serious error on build or execution. I can only load and play videos. Nothing else. No waveform, no ability to enter lines.

output when running is

```
$ XDG_DATA_HOME=pkg/arch/pkg/subtitlecomposer/usr/share src/subtitlecomposer
Loaded VideoPlayer plugin "GStreamer" from "/home/gcb/SubtitleComposer/src/videoplayerplugins/gstreamer/gstplayer.so"
Loaded VideoPlayer plugin "MPlayer" from "/home/gcb/SubtitleComposer/src/videoplayerplugins/mplayer/mplayer.so"
Loaded VideoPlayer plugin "Phonon" from "/home/gcb/SubtitleComposer/src/videoplayerplugins/phonon/phononplayer.so"
Loaded VideoPlayer plugin "Xine" from "/home/gcb/SubtitleComposer/src/videoplayerplugins/xine/xineplayer.so"
QObject::connect: No such signal Phonon::VLC::MediaObject::angleChanged(int)
QObject::connect: No such signal Phonon::VLC::MediaObject::availableAnglesChanged(int)
No such XML file "pkg/arch/pkg/subtitlecomposer/usr/share/kxmlgui5/subtitlecomposer/subtitlecomposerui.rc"
KROSS interpreters: ("qtscript")
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = subtitlecomposer path = /home/gcb/SubtitleComposer/src pid = 15940
KCrash: Arguments: /home/gcb/SubtitleComposer/src/subtitlecomposer 
KCrash: Attempting to start /usr/lib/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
<<<here I select File>Quit. the only option in the File menu>>>
[3]+  Stopped                 XDG_DATA_HOME=pkg/arch/pkg/subtitlecomposer/usr/share src/subtitlecomposer
```

the only odd thing message is about the xml file not existing...
```
ls -la pkg/arch/pkg/subtitlecomposer/usr/share/kxmlgui5/subtitlecomposer/subtitlecomposerui.rc
-rw-r--r-- 1 gcb gcb 5792 Jul  4 22:51 pkg/arch/pkg/subtitlecomposer/usr/share/kxmlgui5/subtitlecomposer/subtitlecomposerui.rc
```
(paths are odd as I tried to build with makepkg at first and I am using the share dir from there...)

I will clean everything and follow the steps on the wiki again, but let me know if this is currently broken and I should use a specific branch.

**Comment by maxrd2** [comment]
Your build cannot open .../kxmlgui5/subtitlecomposer/subtitlecomposerui.rc
Maybe it will work if you put absolute path in XDG_DATA_HOME.
Nothing should be broken in current build.
There is also subtitlcomposer-git package in AUR, not sure what exactly you are trying to do, but would be probably easier to build/install using that.

**Comment by gcb** [comment]
lol. gstreamer was my very last choice :) guess i will just get a debian vm and build there.

**Comment by shirishag75** [comment]
any luck, I was trying today and it didn't work. 

See - 

```
Application::postEvent: Unexpected null receiver
QCoreApplication::po
```

The full error is something like this - 

Please pm me if you need more guidance on ow to produce. I do have the latest in debian - 

Please let me know if you need any help in diagnosing the iw

**Comment by maxrd2** [comment]
Here are the build instructions:
https://github.com/maxrd2/SubtitleComposer/wiki/Building-from-sources
Note last steps on launching the app.
You are probably better off using AppImage.

**Comment by gcb** [comment]
I ended up creating the sub file manually at the time :(

Will keep the build instructions handy for next time! thanks

**Comment by shirishag75** [comment]
> Here are the build instructions:
> https://github.com/maxrd2/SubtitleComposer/wiki/Building-from-sources
> Note last steps on launching the app.
> You are probably better off using AppImage.

I was able to get almost all the dependencies and only one isn't there libgstreamer-plugins-good1.0-dev

**Comment by maxrd2** [comment]
This one https://packages.ubuntu.com/xenial/libgstreamer-plugins-good1.0-dev?
If you managed to compile without that one, you don't need it. Definitely it's not the cause of not working menu.
Missing menu is due to application being unable to find subtitlecomposerui.rc file.
That file is searched in /usr/share, /usr/local/share and $XDG_DATA_HOME. If you are not installing binaries in /usr or /usr/local make sure that you set env variable XDG_DATA_HOME to install_prefix/share and then start application. That is done in step 7 here: https://github.com/maxrd2/SubtitleComposer/wiki/Building-from-sources
