### ISSUE TITLE
Win32 binary release

### ISSUE THREAD

**Issue by maxrd2** [maxrd2/SubtitleComposer#140]
Have uploaded win32 build and install here: https://github.com/maxrd2/SubtitleComposer/releases/tag/win32

Would appreciate some feedback on:
- It should have native look - if not have probably missed some Qt plugin
- Loading of various subtitle formats both text and image (vobsub, PGS, etc)
- MPV player plugin should work fine - please let me know if you encounter some video/dvd/bluray it doesn't want to open
- Waveform should render fine - otherwise let me know please
- GStreamer player backend is not working - if it's working for you please let me know :)
- MPlayer backend - should work if you install mplayer.exe somewhere and configure path - please let me know

TODO:
- Subtitle open/save dialogs should be reworked - issue #115
- Speech recognition is not compiled in yet, if someone wants to make mingw-w64 pocketsphinx/sphinxbase PKGBUILDs please make a pull request here: https://github.com/maxrd2/arch-repo
- Spell checking plugins are not included yet
- Something else?

**Comment by Martchus** [comment]
Seems like you're building this with the packages from the AUR including my Qt 5 packages. Note that you could use my binary repo. There are packages missing but at least you wouldn't need to build everything from scratch.

Do you also use ffmpeg from the AUR for MPV? I'm just curious because last time I tried ffmpeg from the AUR (ffmpeg.exe itself) it was broken.

**Comment by maxrd2** [comment]
Yes, most of the packages are yours and from AUR. I probably would build this without those (and your binary repo) so thank you!
I've made a repo here https://github.com/maxrd2/arch-repo/ together with docker and binary repo. I did so because some packages were missing (have pushed all to AUR), some packages needed a change (will notify maintainers on those) and i wanted to have stable build environment that wont change.. there are like 150+ packages needed.
I haven't tried ffmpeg.exe but libraries are working fine and i haven't modified AUR's ffmpeg.

**Comment by Martchus** [comment]
> i wanted to have stable build environment that won't change
> will notify maintainers - don't think i can just push them

Sounds like a reasonable approach :-)  
I usually do the same when I notice that packages need a change (for my use-cases).

> but libraries are working fine and i haven't modified AUR's ffmpeg

Good to hear.

**Comment by Katarn** [comment]
As I see, the KDE translation files are not included in the installation package.

![image](https://user-images.githubusercontent.com/6339978/60902318-1692b780-a278-11e9-9a21-c464e02fc67d.png)

**Comment by Katarn** [comment]
Also in the dialog windows is not enough paddings. (I can’t say for sure now whether this is a bug of Windows build or is it a common bug for all platforms.)

![image](https://user-images.githubusercontent.com/6339978/60902508-68d3d880-a278-11e9-841b-6457c046080f.png)

**Comment by maxrd2** [comment]
> Also in the dialog windows is not enough paddings. (I can’t say for sure now whether this is a bug of Windows build or is it a common bug for all platforms.)

Think ui on these dialogs has to be fixed in app

**Comment by maxrd2** [comment]
UI padding/margin and locale issue should be good now.
