### ISSUE TITLE
Subtitle Composer icon is incorrect on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [maxrd2/SubtitleComposer#141]
Hi
I use SC 0.7 on Arch Linux.
As we can see in the screenshot below, SC has a Wayland generic icon when
running on Wayland session. The same icon appears in the alt+tab menu.
Maybe this link can help you
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

![composer](https://user-images.githubusercontent.com/15967631/61578293-cebb2e00-aaca-11e9-9793-ec693fd926ae.png)

**Comment by maxrd2** [comment]
Should be fixed now.
Thanks for report.
