### ISSUE TITLE
OCR does not work properly for blu-ray subtitles

### ISSUE THREAD

**Issue by rschouwenburg** [maxrd2/SubtitleComposer#145]
When I OCR blu-ray subtitles, it keeps asking me to enter the letters. It is not learning / learning very slowly. Maybe something to do with the higher resolution of the images?

Here is a sample:
[alien.sup.zip](https://github.com/maxrd2/SubtitleComposer/files/3465411/alien.sup.zip)

**Comment by maxrd2** [comment]
There is no learning algorithm. It's just dumb matching of character bitmaps which doesn't work so well with antialiased bluray titles.
Will implement some configurable fuzzy matching or add some learning algorithm to detect characters.

**Comment by maxrd2** [comment]
Issue was moved here: https://invent.kde.org/kde/subtitlecomposer/issues/4
