### ISSUE TITLE
No waveform with specific mkv

### ISSUE THREAD

**Issue by duck7000** [maxrd2/SubtitleComposer#146]
The Waveform is not working with this mkv file:

ffmpeg -i DARK.S01E01.720p.NF.WEBRip.DD5.1.x264-NTb.mkv
ffmpeg version 4.1.3-0york1~18.04 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --prefix=/usr --extra-version='0york1~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-nonfree --enable-libfdk-aac --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version='0york1~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-nonfree --enable-libfdk-aac --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Guessed Channel Layout for Input Stream #0.1 : 5.1
Input #0, matroska,webm, from 'DARK.S01E01.720p.NF.WEBRip.DD5.1.x264-NTb.mkv':
  Metadata:
    encoder         : libebml v1.3.5 + libmatroska v1.4.5
    creation_time   : 2017-12-01T19:21:37.000000Z
  Duration: 00:51:30.29, start: 0.000000, bitrate: 4365 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1280x640, SAR 1:1 DAR 2:1, 24 fps, 24 tbr, 1k tbn, 48 tbc (default)
    Metadata:
      BPS             : 3916730
      BPS-eng         : 3916730
      DURATION        : 00:51:30.292000000
      DURATION-eng    : 00:51:30.292000000
      NUMBER_OF_FRAMES: 74167
      NUMBER_OF_FRAMES-eng: 74167
      NUMBER_OF_BYTES : 1512980119
      NUMBER_OF_BYTES-eng: 1512980119
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(ger): Audio: eac3, 48000 Hz, 5.1, fltp (default)
    Metadata:
      BPS             : 448000
      BPS-eng         : 448000
      DURATION        : 00:51:16.000000000
      DURATION-eng    : 00:51:16.000000000
      NUMBER_OF_FRAMES: 96125
      NUMBER_OF_FRAMES-eng: 96125
      NUMBER_OF_BYTES : 172256000
      NUMBER_OF_BYTES-eng: 172256000
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: subrip
    Metadata:
      BPS             : 40
      BPS-eng         : 40
      DURATION        : 00:50:57.916000000
      DURATION-eng    : 00:50:57.916000000
      NUMBER_OF_FRAMES: 468
      NUMBER_OF_FRAMES-eng: 468
      NUMBER_OF_BYTES : 15390
      NUMBER_OF_BYTES-eng: 15390
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(bul): Subtitle: subrip
    Metadata:
      BPS             : 62
      BPS-eng         : 62
      DURATION        : 00:48:15.416000000
      DURATION-eng    : 00:48:15.416000000
      NUMBER_OF_FRAMES: 468
      NUMBER_OF_FRAMES-eng: 468
      NUMBER_OF_BYTES : 22635
      NUMBER_OF_BYTES-eng: 22635
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(fre): Subtitle: subrip
    Metadata:
      BPS             : 41
      BPS-eng         : 41
      DURATION        : 00:50:57.875000000
      DURATION-eng    : 00:50:57.875000000
      NUMBER_OF_FRAMES: 441
      NUMBER_OF_FRAMES-eng: 441
      NUMBER_OF_BYTES : 15872
      NUMBER_OF_BYTES-eng: 15872
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(ger): Subtitle: subrip
    Metadata:
      BPS             : 49
      BPS-eng         : 49
      DURATION        : 00:47:54.208000000
      DURATION-eng    : 00:47:54.208000000
      NUMBER_OF_FRAMES: 533
      NUMBER_OF_FRAMES-eng: 533
      NUMBER_OF_BYTES : 17811
      NUMBER_OF_BYTES-eng: 17811
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:6(ita): Subtitle: subrip
    Metadata:
      BPS             : 41
      BPS-eng         : 41
      DURATION        : 00:50:58.792000000
      DURATION-eng    : 00:50:58.792000000
      NUMBER_OF_FRAMES: 441
      NUMBER_OF_FRAMES-eng: 441
      NUMBER_OF_BYTES : 15807
      NUMBER_OF_BYTES-eng: 15807
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:7(rum): Subtitle: subrip
    Metadata:
      BPS             : 41
      BPS-eng         : 41
      DURATION        : 00:49:15.416000000
      DURATION-eng    : 00:49:15.416000000
      NUMBER_OF_FRAMES: 462
      NUMBER_OF_FRAMES-eng: 462
      NUMBER_OF_BYTES : 15231
      NUMBER_OF_BYTES-eng: 15231
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:8(spa): Subtitle: subrip
    Metadata:
      BPS             : 42
      BPS-eng         : 42
      DURATION        : 00:50:58.833000000
      DURATION-eng    : 00:50:58.833000000
      NUMBER_OF_FRAMES: 467
      NUMBER_OF_FRAMES-eng: 467
      NUMBER_OF_BYTES : 16252
      NUMBER_OF_BYTES-eng: 16252
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:9(tur): Subtitle: subrip
    Metadata:
      BPS             : 38
      BPS-eng         : 38
      DURATION        : 00:50:58.833000000
      DURATION-eng    : 00:50:58.833000000
      NUMBER_OF_FRAMES: 464
      NUMBER_OF_FRAMES-eng: 464
      NUMBER_OF_BYTES : 14689
      NUMBER_OF_BYTES-eng: 14689
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
![Screenshot from 2019-08-06 11-14-32](https://user-images.githubusercontent.com/15360048/62527477-7f4f5e80-b83b-11e9-99ee-d1cd20f964eb.png)

**Comment by maxrd2** [comment]
Can you please paste subtitlecomposer output?

**Comment by duck7000** [comment]
Output from what exactly?
The waveform widget is empty
![Screenshot from 2019-08-06 23-13-43](https://user-images.githubusercontent.com/15360048/62577798-fddde780-b89f-11e9-9c93-ac7f926ad6a0.png)

This is the terminal output when loading this subtitle:
```
subtitlecomposer DARK.S01E01.720p.NF.WEBRip.DD5.1.x264-NTb.srt
qt5ct: using qt5ct plugin
Loaded PlayerBackend "GStreamer" from "/usr/lib/x86_64-linux-gnu/subtitlecomposer/gstplayer.so"
Loaded PlayerBackend "MPlayer" from "/usr/lib/x86_64-linux-gnu/subtitlecomposer/mplayer.so"
Loaded PlayerBackend "MPV" from "/usr/lib/x86_64-linux-gnu/subtitlecomposer/mpvplayer.so"
Loaded PlayerBackend "Phonon" from "/usr/lib/x86_64-linux-gnu/subtitlecomposer/phononplayer.so"
Loaded PlayerBackend "Xine" from "/usr/lib/x86_64-linux-gnu/subtitlecomposer/xineplayer.so"
qt5ct: D-Bus global menu: no
Loaded SpeechPlugin "PocketSphinx" from "/usr/lib/x86_64-linux-gnu/subtitlecomposer/pocketsphinxasr.so"
KROSS interpreters: ("qtscript")
Input #0, srt, from '/media/Series/Dark/Season 1/DARK.S01E01.720p.NF.WEBRip.DD5.1.x264-NTb.srt':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Subtitle: subrip
[AVIOContext @ 0x55ee424f7440] Statistics: 29559 bytes read, 0 seeks
[MPV: cplayer ]  info :  Playing: /media/Series/Dark/Season 1/DARK.S01E01.720p.NF.WEBRip.DD5.1.x264-NTb.mkv

[MPV: cplayer ]  info :   (+) Video --vid=1 (*) (h264 1280x640 24.000fps)

[MPV: cplayer ]  info :   (+) Audio --aid=1 --alang=ger (*) (eac3 6ch 48000Hz)

[MPV: cplayer ]  info :       Subs  --sid=1 --slang=eng (subrip)

[MPV: cplayer ]  info :       Subs  --sid=2 --slang=bul (subrip)

[MPV: cplayer ]  info :       Subs  --sid=3 --slang=fre (subrip)

[MPV: cplayer ]  info :       Subs  --sid=4 --slang=ger (subrip)

[MPV: cplayer ]  info :       Subs  --sid=5 --slang=ita (subrip)

[MPV: cplayer ]  info :       Subs  --sid=6 --slang=rum (subrip)

[MPV: cplayer ]  info :       Subs  --sid=7 --slang=spa (subrip)

[MPV: cplayer ]  info :       Subs  --sid=8 --slang=tur (subrip)

[MPV: cplayer ]  info :       Subs  --sid=9 'DARK.S01E01.720p.NF.WEBRip.DD5.1.x264-NTb.srt' (subrip) (external)

[h264 @ 0x55ee425f8740] Reinit context to 1280x640, pix_fmt: yuv420p
Input #0, matroska,webm, from '/media/Series/Dark/Season 1/DARK.S01E01.720p.NF.WEBRip.DD5.1.x264-NTb.mkv':
  Metadata:
    encoder         : libebml v1.3.5 + libmatroska v1.4.5
    creation_time   : 2017-12-01T19:21:37.000000Z
  Duration: 00:51:30.29, start: 0.000000, bitrate: 4365 kb/s
    Stream #0:0(eng): Video: h264 (High), 1 reference frame, yuv420p(progressive, left), 1280x640, SAR 1:1 DAR 2:1, 24 fps, 24 tbr, 1k tbn, 48 tbc (default)
    Metadata:
      BPS             : 3916730
      BPS-eng         : 3916730
      DURATION        : 00:51:30.292000000
      DURATION-eng    : 00:51:30.292000000
      NUMBER_OF_FRAMES: 74167
      NUMBER_OF_FRAMES-eng: 74167
      NUMBER_OF_BYTES : 1512980119
      NUMBER_OF_BYTES-eng: 1512980119
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(ger): Audio: eac3, 48000 Hz, 6 channels, fltp (default)
    Metadata:
      BPS             : 448000
      BPS-eng         : 448000
      DURATION        : 00:51:16.000000000
      DURATION-eng    : 00:51:16.000000000
      NUMBER_OF_FRAMES: 96125
      NUMBER_OF_FRAMES-eng: 96125
      NUMBER_OF_BYTES : 172256000
      NUMBER_OF_BYTES-eng: 172256000
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: subrip
    Metadata:
      BPS             : 40
      BPS-eng         : 40
      DURATION        : 00:50:57.916000000
      DURATION-eng    : 00:50:57.916000000
      NUMBER_OF_FRAMES: 468
      NUMBER_OF_FRAMES-eng: 468
      NUMBER_OF_BYTES : 15390
      NUMBER_OF_BYTES-eng: 15390
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(bul): Subtitle: subrip
    Metadata:
      BPS             : 62
      BPS-eng         : 62
      DURATION        : 00:48:15.416000000
      DURATION-eng    : 00:48:15.416000000
      NUMBER_OF_FRAMES: 468
      NUMBER_OF_FRAMES-eng: 468
      NUMBER_OF_BYTES : 22635
      NUMBER_OF_BYTES-eng: 22635
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(fre): Subtitle: subrip
    Metadata:
      BPS             : 41
      BPS-eng         : 41
      DURATION        : 00:50:57.875000000
      DURATION-eng    : 00:50:57.875000000
      NUMBER_OF_FRAMES: 441
      NUMBER_OF_FRAMES-eng: 441
      NUMBER_OF_BYTES : 15872
      NUMBER_OF_BYTES-eng: 15872
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(ger): Subtitle: subrip
    Metadata:
      BPS             : 49
      BPS-eng         : 49
      DURATION        : 00:47:54.208000000
      DURATION-eng    : 00:47:54.208000000
      NUMBER_OF_FRAMES: 533
      NUMBER_OF_FRAMES-eng: 533
      NUMBER_OF_BYTES : 17811
      NUMBER_OF_BYTES-eng: 17811
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:6(ita): Subtitle: subrip
    Metadata:
      BPS             : 41
      BPS-eng         : 41
      DURATION        : 00:50:58.792000000
      DURATION-eng    : 00:50:58.792000000
      NUMBER_OF_FRAMES: 441
      NUMBER_OF_FRAMES-eng: 441
      NUMBER_OF_BYTES : 15807
      NUMBER_OF_BYTES-eng: 15807
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:7(rum): Subtitle: subrip
    Metadata:
      BPS             : 41
      BPS-eng         : 41
      DURATION        : 00:49:15.416000000
      DURATION-eng    : 00:49:15.416000000
      NUMBER_OF_FRAMES: 462
      NUMBER_OF_FRAMES-eng: 462
      NUMBER_OF_BYTES : 15231
      NUMBER_OF_BYTES-eng: 15231
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:8(spa): Subtitle: subrip
    Metadata:
      BPS             : 42
      BPS-eng         : 42
      DURATION        : 00:50:58.833000000
      DURATION-eng    : 00:50:58.833000000
      NUMBER_OF_FRAMES: 467
      NUMBER_OF_FRAMES-eng: 467
      NUMBER_OF_BYTES : 16252
      NUMBER_OF_BYTES-eng: 16252
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:9(tur): Subtitle: subrip
    Metadata:
      BPS             : 38
      BPS-eng         : 38
      DURATION        : 00:50:58.833000000
      DURATION-eng    : 00:50:58.833000000
      NUMBER_OF_FRAMES: 464
      NUMBER_OF_FRAMES-eng: 464
      NUMBER_OF_BYTES : 14689
      NUMBER_OF_BYTES-eng: 14689
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-01 19:21:37
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-01 19:21:37
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Error resampling audio frame Input changed (This error repeat a few hundred times)
[MPV: cplayer ]  info :  AO: [pulse] 48000Hz 5.1(side) 6ch float
[MPV: cplayer ]  info :  VO: [opengl] 1280x640 yuv420p
[AVIOContext @ 0x55ee41fe5000] Statistics: 1686143458 bytes read, 3 seeks
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
```

**Comment by maxrd2** [comment]
Should be fixed now. Thanks for reporting.

**Comment by duck7000** [comment]
Thanks for the fix, it's working fine!
