### ISSUE TITLE
Vobsub subtitle streams sometimes use duration instead of hide time

### ISSUE THREAD

**Issue by rschouwenburg** [maxrd2/SubtitleComposer#148]
If you import the vobsub subtitle stream below, you get the duration in the hide time.

[s01e01.zip](https://github.com/maxrd2/SubtitleComposer/files/3537389/s01e01.zip)

Would it be possible to detect this and correct?

As always, thanks for SubtitleComposer! It's awesome.

**Comment by maxrd2** [comment]
Could you please provide me with both .idx and .sub file?

**Comment by rschouwenburg** [comment]
Apologies.. I had to find another example. Here it is.

[s01e01-2.zip](https://github.com/maxrd2/SubtitleComposer/files/3796184/s01e01-2.zip)

**Comment by maxrd2** [comment]
that one also contains just .idx and no .sub

**Comment by rschouwenburg** [comment]
Ok, this time it's right.

[s01e01-2.zip](https://github.com/maxrd2/SubtitleComposer/files/3799893/s01e01-2.zip)

**Comment by maxrd2** [comment]
Ok.. so this seems same as #129, problem is broken ffmpeg version you're using.
I get correct end times here:
![image](https://user-images.githubusercontent.com/1187381/68074333-23449980-fd9a-11e9-9547-56fabc6462af.png)
Please try using AppImage instead of ubuntu PPA builds.

**Comment by rschouwenburg** [comment]
Yes, I solely use the AppImage version (0.7.0). Anything I can look into?

**Comment by rschouwenburg** [comment]
I was curious and tried the development build AppImage. That one does indeed work correctly.

**Comment by rschouwenburg** [comment]
Unfortunately the development build suffers from #142 

![Screenshot from 2019-11-02 17-12-16](https://user-images.githubusercontent.com/17439419/68077580-3a808880-fd94-11e9-84aa-206e07e17481.png)

**Comment by rschouwenburg** [comment]
Ignore that last one. This only happened with one specific episode. Others are fine. Attached the original VOBSUB if you're interested.

[s03e03.zip](https://github.com/maxrd2/SubtitleComposer/files/3801006/s03e03.zip)

**Comment by maxrd2** [comment]
great... thanks will try to improve whitespace detection some more, or make it configurable

**Comment by rschouwenburg** [comment]
Ok, thank you! To be clear, v0.7 has no problem properly detecting the white spaces on this particular file, just the development version.

**Comment by maxrd2** [comment]
Issue was moved here: https://invent.kde.org/kde/subtitlecomposer/issues/5
