### ISSUE TITLE
Can't find ANSI as char set

### ISSUE THREAD

**Issue by rmlazzari** [maxrd2/SubtitleComposer#153]
Hi, I'm not sure it's exactly an issue but... I'd like to set ANSI instead of UTF-8 as default char set in Subtitle Composer but I can't find the ANSI set browsing the field "Default subtitles enconding". Could you please help me?

Thank you in advance.

**Comment by maxrd2** [comment]
You probably want one of western european charsets. Maybe ISO 8859-1

**Comment by rmlazzari** [comment]
Thank you, maxrd2. I'm talking about Portuguese. After asking you I search a lot in Internet and, indeed, I've found no references as exactly "ANSI". ANSI, as far as I understood, is a "family" of chars, a standard for may sets. I'm far from an expert with IT so, please, excuse some newbie question. I believe Subtitle Composer already have a set as option equivalent to the Windows' Notepad call "ANSI". I'm new in Linux, I've changed because a granddaughter say it's better.

If you don't mind I'm sending you a file that use the standard called ANSI to help me find the best option in you program. Almost all files I have with subtitles (99,9%) are in that standard. If it don't boring you, could you say what standard is that?



[Vision.zip](https://github.com/maxrd2/SubtitleComposer/files/3590897/Vision.zip)

**Comment by Martchus** [comment]
Use UTF-8 instead of "ANSI" or anything else unless you have to work with legacy software which doesn't support UTF-8.

By the way: https://en.wikipedia.org/wiki/ANSI_character_set

**Comment by rmlazzari** [comment]
Thank you, Martchus. Actually I use MKVToolNix to create the final file, which will contains video, sound and subtitles together. I'm not sure but I believe this "joiner" program must have an option to handle UTF-8 files. Although the chars appear right in the Subtitle Composer, when I play the final .MKV, the VLC shows me estrange chars. And the most of subtitle's files I receive are in an "ANSI" (whatever it is) code.

As a try, I will as soon as possible, try to convert these subtitle files into UTF-8 and search an option, in MKVToolNix, to use this codification. I'll report the results, it could be useful for somebody...

Thank you again for answer and patience.

**Comment by maxrd2** [comment]
closing this issue... feel free to reopen if you have more issues
