### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by hyuma78** [maxrd2/SubtitleComposer#155]
I've noticed an italian error on menu "Modifica". There is "Sostituiscei" word, but should be "Sostituisci".

**Comment by maxrd2** [comment]
Italian localization is a bit outdated.
Help is welcome. If you'd like to translate/fix some strings you can do so from here: https://crowdin.com/translate/subtitlecomposer/6/en-it

**Comment by hyuma78** [comment]
Ok, I will check in! Thanks and greetings from Italy, I'm Thomas and I'm
happy to help!

Il dom 13 ott 2019, 23:12 Mladen Milinkovic <notifications@github.com> ha
scritto:

**Comment by maxrd2** [comment]
Thank you!
