### ISSUE TITLE
Add webvtt Saving/Export Support

### ISSUE THREAD

**Issue by CornMaster** [maxrd2/SubtitleComposer#157]
Hello,
I'm using this to create subtitles/closed captions for web streamed videos and it would be great to have the option to save to webvtt natively.  I know that you can easily convert from .srt to .vtt with a number of command line programs (and I will until native support is included), but it would be great if this was included out of the box.

Additionally, I could perhaps create a plugin to do this automatically.  I see that Javascript and Python are supported, and I have some experience with those languages.  Is there any documentation available on the functions/methods available when programming in the various languages?

Thanks for your work on this.

**Comment by maxrd2** [comment]
It's not possible to add subtitle formats in scripting languages right now.
Will add asap, already had it on my radar.

**Comment by maxrd2** [comment]
Issue was moved here: https://invent.kde.org/kde/subtitlecomposer/issues/3
