### ISSUE TITLE
update changelog in Subtitle composer alpha 

### ISSUE THREAD

**Issue by shirishag75** [maxrd2/SubtitleComposer#159]
I tried to see what changes were in subtitle-composer alpha as shared[ here](https://github.com/maxrd2/SubtitleComposer/archive/continuous.tar.gz). After extraction the changelog just shows the changes till 0.7.0 but nothing after that. Hope you can remedy that situation.

**Comment by maxrd2** [comment]
Changelog is updated manually when new version is tagged (right now it's 0.7.0).
You can see complete list of changes in git here: https://invent.kde.org/kde/subtitlecomposer/commits/master
