### ISSUE TITLE
Autosave feature

### ISSUE THREAD

**Issue by codesearcher** [maxrd2/SubtitleComposer#160]
> Add feature to save undo history to temp file. Once app closes this file is deleted. If app/system crashes and file stays on disk, on next start app will notice the file and prompt user to recover. Whole state and undo history would be restored.
> 
> Add an option to perform auto saving every N minutes. It can be setup to:
> 
>     * disabled
> 
>     * save to .bak extension
> 
>     * overwrite original file

The issue isn't "new".... but would be very good have this feature :-)

**Comment by maxrd2** [comment]
This is duplicate of #113
