### ISSUE TITLE
Subtitle composer, waveform still missing

### ISSUE THREAD

**Issue by Hamal24** [maxrd2/SubtitleComposer#165]
I asked in issue #164 how I can find the waveform in subtitle composer. User Maxrd2 kindly answered this question for me and I was also able to find the checkbox that I have to tick.

Unfortunately the waveform is still missing. I have the latest version of subtitle composer (0.7.0-1build2) for Linux Mint 20 cinnamon 4.6.7.

It once happened that the waveform was minimized to the point that it disappeared in a corner of the monitor. No idea how it happened, but I found it again then. But this is not the case now. Does anyone know what else can be done?

Thanks in advance!

**Comment by maxrd2** [comment]
please report bugs on KDE bug tracker
