### ISSUE TITLE
mpv support

### ISSUE THREAD

**Issue by muzena** [maxrd2/subtitlecomposer#21]
Pozdrav.
Jel moguće da dodaš podršku za mpv plejer, fork mplayera i mplayera2, ako nije problem.
https://github.com/mpv-player/mpv/blob/master/DOCS/man/changes.rst
http://mpv.io/

**Comment by muzena** [comment]
Ne radi dvostruki klik s mišem na video površinu, ako hoćeš povećat u fullscreen.
Ne znam jel to subtitle composer ili mpv bug!?
I još sam promjetio da ne radi vaapi hardversko ubrzanje na ATI gfrafičkoj kartici s instaliranim vlasničkim ATI driverima.
To je dodano u Catalyst 14.12 vaapi hardversko ubrzanje:
http://wiki.cchtml.com/index.php/Ubuntu_Trusty_Installation_Guide#Hardware_Video_Decode_Acceleration.

**Comment by maxrd2** [comment]
Can we please continue in english in case someone else has same issue?
Will fix doubleclick and fullscreen issue soon.

Do you have vaapi set here?
![screenshot](https://cloud.githubusercontent.com/assets/1187381/5979806/339d89c0-a8ab-11e4-8386-7a6e8fb9742b.jpg)

Can you show me output of following command? Does it have 'vaapi' listed?
$ mpv --vo help

**Comment by muzena** [comment]
I have tested vaapi in Smplayer, and it work.

mpv --vo help
Available video outputs:
  opengl         : Extended OpenGL Renderer
  vdpau          : VDPAU with X11
  xv             : X11/Xv
  vaapi          : VA API with X11
  x11            : X11 ( XImage/Shm )
  null           : Null video output
  image          : Write video frames to image files
  opengl-hq      : Extended OpenGL Renderer (high quality rendering preset)
  opengl-cb      : OpenGL Callbacks for libmpv

**Comment by maxrd2** [comment]
Can you please start subtitlecomposer from terminal and paste me the output here.. specifically lines when it starts playing video. You should see something like this:
```
subtitlecomposer(19784) SubtitleComposer::MPVBackend::mpvEventHandle: [MPV: cplayer ]  info :  Playing: /home/max/Media/sirius.avi
subtitlecomposer(19784) SubtitleComposer::MPVBackend::mpvEventHandle: [MPV: cplayer ]  info :  [stream] Video (+) --vid=1 (mpeg4)
subtitlecomposer(19784) SubtitleComposer::MPVBackend::mpvEventHandle: [MPV: cplayer ]  info :  [stream] Audio (+) --aid=1 (mp3)
subtitlecomposer(19784) SubtitleComposer::MPVBackend::mpvEventHandle: [MPV: cplayer ]  info :  File tags:
subtitlecomposer(19784) SubtitleComposer::MPVBackend::mpvEventHandle: [MPV: cplayer ]  info :   encoder: VirtualDubMod 1.5.10.2 (build 2540/release)
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
subtitlecomposer(19784) SubtitleComposer::MPVBackend::mpvEventHandle: [MPV: cplayer ]  info :  AO: [pulse] 48000Hz stereo 2ch s16     
subtitlecomposer(19784) SubtitleComposer::MPVBackend::mpvEventHandle: [MPV: cplayer ]  info :  VO: [vaapi] 624x352 yuv420p            
```

**Comment by maxrd2** [comment]
Made another commit. Please try now. If it doesn't work try changing "Hardware Video Decoding" setting under MPV to vaapi from auto

**Comment by muzena** [comment]
linux@mint ~ $ subtitlecomposer
Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/fglrx_drv_video.so
libva info: Found init function __vaDriverInit_0_33
libva info: va_openDriver() returns 0
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/fglrx_drv_video.so
libva info: Found init function __vaDriverInit_0_33
libva info: va_openDriver() returns 0

**Comment by maxrd2** [comment]
Vaapi seems to have initialized fine. HW video decoding is independent of video output driver on mpv.
It should work fine if you set "Hardware Video Decoding" to auto or vaapi in subtitlecomposer settings.
You will find that setting in commit d99be15, so make sure you use latest git version.

After enabling that you will see similar output which means that hw decoding is working.
```
libva info: va_openDriver() returns 0
subtitlecomposer(27441) SubtitleComposer::MPVBackend::mpvEventHandle: [MPV: vd ]  info :  Trying to use hardware decoding.
```

**Comment by muzena** [comment]
Super, sad sve radi!
Jel možeš reći jel ova phonon zakrpa potrebna ili je to specifična zakrpa za ubuntu i derivate?
https://github.com/maxrd2/subtitlecomposer/blob/master/pkg/debian/patches/03_link_phonon.diff

**Comment by maxrd2** [comment]
Izgleda mi nepotrebno.. phonon libs su vec dodani u src/main/CMakeLists.txt.
Super... zatvaram

**Comment by muzena** [comment]
Above and below screenshot errors. It's visible part of the desktop.
And below it's visible double subtitles.
![screenshot from 2015-02-03 21 52 52](https://cloud.githubusercontent.com/assets/1978777/6029482/40c8ff6e-abf1-11e4-9d8c-8fb795858b78.png)

**Comment by maxrd2** [comment]
Can you reproduce it every time?
Does it still happen if you turn off vaapi acceleration?

**Comment by muzena** [comment]
When is vaapi disabled and xv enabled fullscreen works normally.

**Comment by maxrd2** [comment]
This seems a lot like a problem in libmpv or amd's vaapi.
I've been using libmpv backend with intel's vaapi and didn't have issues so far.
Is your SC compiled with Xine backend?

**Comment by muzena** [comment]
In Smplayer fullscreen work with vaapi enabled.
During compilation only libxine2-dev and libxine2-bin are installed of xine library.
This is buildlog link: 
https://launchpadlibrarian.net/196486475/buildlog_ubuntu-trusty-amd64.subtitlecomposer_0.5.7.5~trusty_UPLOADING.txt.gz

**Comment by maxrd2** [comment]
smplayer doesn't use libmpv

**Comment by muzena** [comment]
He, he!
Look this link:
https://github.com/u8sand/Baka-MPlayer/issues/91

**Comment by maxrd2** [comment]
I'm 99% sure this is upstream issue.. either libmpv, or something it uses.
Please create an issue with libmpv here https://github.com/mpv-player/mpv/issues I would do it, but am not sure of details on your system.
If you paste link here will join the conversation
