### ISSUE TITLE
ASS advanced styles

### ISSUE THREAD

**Issue by SafaAlfulaij** [maxrd2/SubtitleComposer#24]
> Support for multiple formats, including SubRip, MicroDVD, SSA/ASS (without advanced styles), MPlayer, TMPlayer and YouTube captions.

Why not advanced styles?

**Comment by maxrd2** [comment]
Because there isnt code written that does something with advanced ssa styles.. and everything not supported on ssa gets stripped away during save.
Also personally havent came across many (any?) Ssa files containing advanced styles

**Comment by maxrd2** [comment]
http://docs.aegisub.org/manual/ASS_Tags

**Comment by maxrd2** [comment]
Issue moved here: https://invent.kde.org/kde/subtitlecomposer/issues/14
