### ISSUE TITLE
Auto translation doesn't work

### ISSUE THREAD

**Issue by Rui-Santos** [maxrd2/SubtitleComposer#25]
When using the Google service to translate I always get

```
There was an error performing the translation:

Unexpected contents received from translation service
```

SubtitleComposer v0.5.7
Ubuntu 14.04 x64

**Comment by maxrd2** [comment]
Google Translate API is no longer free to use, so it's not working anymore.
To use it you should signup and buy api keys from google.
If you're interested please let me know and will update this part to support paid google translate api.

**Comment by psyvisions** [comment]
Hey, what about Bing/Microsoft? They have a free tier with 2million chars of use. http://datamarket.azure.com/dataset/bing/microsofttranslator

**Comment by maxrd2** [comment]
will look into it and add it asap

**Comment by duck7000** [comment]
Well according to this google page v3 is still free but limited to 500000 characters a month?
https://cloud.google.com/translate/pricing

It would be awesome if this is going to work again, and 500000 is about nearly 10 subtitles per month, that should be enough?

**Comment by maxrd2** [comment]
Yes there is free amount of characters you can translate, but the API changed and it requires OAuth authentication. Have already made some work on new Google API.
Once that is working again will start on Bing/Microsoft API.

**Comment by duck7000** [comment]
Thanks for the info!

**Comment by maxrd2** [comment]
Issue moved here: https://invent.kde.org/kde/subtitlecomposer/issues/13

**Comment by JuergenFB** [comment]
Please add translation by https://deepl.com
