### ISSUE TITLE
Adding video to sync to creates an error in Kubuntu 15.04

### ISSUE THREAD

**Issue by Allan-Shand** [maxrd2/subtitlecomposer#27]
I am using version 0.5.3 from the Ubuntu repositories on Kubuntu 15.04 and when I add a video I get this non descriptive error 

![snapshot12](https://cloud.githubusercontent.com/assets/2791233/7821034/fb0f67a6-03e3-11e5-8f2c-daffe7d0aa9f.png)

in terminal I get this message

`** Message: don't know how to handle video/x-h264, level=(string)4, profile=(string)main, codec_data=(buffer)014d4028ffe10020674d4028eca0581bfc9ff80200016b505010640000030004000afc803c60c65801000568ebe1b3c8, stream-format=(string)avc, alignment=(string)au, width=(int)704, height=(int)426, pixel-aspect-ratio=(fraction)91/64, framerate=(fraction)25/1                                                       
X Error: BadWindow (invalid Window parameter) 3                                                                                                                                                           
  Major opcode: 20 (X_GetProperty)                                                                                                                                                                        
  Resource id:  0x620016c                                                                                                                                                                                 
X Error: BadWindow (invalid Window parameter) 3                                                                                                                                                           
  Major opcode: 20 (X_GetProperty)                                                                                                                                                                        
  Resource id:  0x62001b3`

**Comment by maxrd2** [comment]
which video player backend do you use/have setup?
If it's gstreamer, please check you have installed gstreamer codec packages.

**Comment by Allan-Shand** [comment]
OK I have switched to VLC backend for phonon and added this PPA from launchpad 

https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/subtitlecomposer

which I guess is building directly from your git hub repository I am now at version 0.5.7.4 and everything is working fine you can close this issue as fixed I should have checked my version before raising the issue... must be getting old ;)
