### ISSUE TITLE
No more generation of '.mo' files during compilation

### ISSUE THREAD

**Issue by david-geiger** [maxrd2/subtitlecomposer#31]
Hi,

I tried to compile, on Mageia Cauldron,  subtitlecomposer with a snapshot from latest commit 0fe91f59954155f1d7331016bb73ea3ad9a06e65 but I get an .mo files generation issue, during compilation all .mo files are no more generate:

Here past the full compile log:

http://pastebin.com/sF1SrFqt

Best Regards,
David

**Comment by maxrd2** [comment]
hi David,
thanks for reporting it.
should be all good now.
-Max

**Comment by david-geiger** [comment]
Hi Max,

Thanks for your fix, I'll try a new compile.

Just a warning : I see in CMakeList.txt from ´po ´ that it is missing italian translation 

Something like "add_subdirectory(it)"

**Comment by maxrd2** [comment]
That one was never been included in build...
thanks

**Comment by david-geiger** [comment]
Ok cool :)

Can you regenerate the 0.5.8 tarball including recent changes?

**Comment by maxrd2** [comment]
made 0.5.9 with some more changes
