### ISSUE TITLE
Waveform as a draggable widget, custom colours, scrolling, and line adjustment enhancement

### ISSUE THREAD

**Issue by lunarrunner** [maxrd2/subtitlecomposer#39]
First of all, thank you for your work on Subtitle Composer! I really like the waveform that has been implemented recently.

I have a couple of suggestions on how the waveform could be made better:

1. The colours could be customizable. Personally, I find the beginning and the end position of the lines difficult to notice on the waveform. Perhaps if these points were marked with a lighter colour, that would be better.
1. IMO, the waveform should be scrollable by the user even if autoscroll is enabled.
1. It would be great if both the beginning and end points of a line could be adjusted by draging it with the mouse (for example, clicking on anywhere in the middle of a line and holding it down).
1. An option to place the start or end of the currently selected line exactly where I click while holding down CTRL or SHIFT respectively. (Or CTRL+Left Click for the start, CTRL+Right Click for the end.) This behaviour would be something similar that can be found in Subtitle Editor and Subtitle Edit.
1. An option to make the waveform horizontal instead of vertical and the possibility to drag it anywhere within the window as a widget (in the latter case, just like kdenlive).

**Comment by maxrd2** [comment]
Thanks a lot for your suggestions/feedback. I plan to add settings page where it will be possible to define colors and everything that is look related.

1. There is already brighter line, once its configurable it should be possible to make it even brighter.
2. It would continue switching back after time reaches page border, not sure if it would become annoying. What exactly did you have in mind? Disable autoscroll temporarily when user starts scrolling and/or while mouse is hovering widget?
3. They became draggable in one of the recent commits. Are you sure you are using latest version? 0.6.2 was tagged yesterday.
4. To adjust currently selected line in listing widget that is being edited?
5. I guess i could make it an option at some point, it will be configurable, but am not sure about dragging it around from one border to other.

**Comment by Martchus** [comment]
To 5: I actually already thought about adding this feature. It would be really easy to implement. The video player should be dragable, too (just as in kdenlive as you mentioned).

**Comment by lunarrunner** [comment]
> It would continue switching back after time reaches page border, not sure if it would become annoying. What exactly did you have in mind? Disable autoscroll temporarily when user starts scrolling and/or while mouse is hovering widget?

You are right. To me, temporarily turning off autoscroll while the user is scrolling sounds like a good idea.

> They became draggable in one of the recent commits. Are you sure you are using latest version? 0.6.2 was tagged yesterday.

I have 0.6.2, installed from the AUR under Manjaro Linux. Yet, dragging doesn't seem to work.

> To adjust currently selected line in listing widget that is being edited?

The one that is selected there with a single click, so whether you enter editing mode by e.g. double clicking on it or not shouldn't matter.

Speaking of which, the one selected there could also be highlighted in the waveform so that it would be easier to distinguish it from the others.

**Comment by Martchus** [comment]
Dragging/docking like in kdeenlive doesn't work because it has not been implemented yet.

**Comment by lunarrunner** [comment]
I meant dragging the representation of a line within the waveform. Also, I've just updated my previous comment for clarity.

**Comment by maxrd2** [comment]
@lunarrunner last commit allows you to drag whole subtitle around the waveform widget.. so point 3 should be done

**Comment by maxrd2** [comment]
1, 2 and 5 are done.
Waveform widget still draw vertically when it's layout is horizontal, will fix that.

**Comment by maxrd2** [comment]
> 4 - An option to place the start or end of the currently selected line exactly where I click while holding down CTRL or SHIFT respectively. (Or CTRL+Left Click for the start, CTRL+Right Click for the end.) This behaviour would be something similar that can be found in Subtitle Editor and Subtitle Edit.

I'm not sure Ctrl+Left/Right Click on waveform will be obvious to people using it. Any ideas how to make it more obvious? 
Maybe it would be better to make a RMB popup menu and display regular entries with shortcut like:
- Set selected line Show Time  Ctrl+SomeKey
- Set selected line Hide Time  Ctrl+SomeKey
- Insert new line Ctrl+SomeKey

**Comment by lunarrunner** [comment]
> Maybe it would be better to make a RMB popup menu and display regular entries with shortcut like:

>  * Set selected line Show Time Ctrl+SomeKey
>  * Set selected line Hide Time Ctrl+SomeKey
>  * Insert new line Ctrl+SomeKey

That's a good idea.

By the way, are there any plans to create a help file? (I can press F1 to bring up KDE help, but it says no documentation found for this program.) This could be mentioned there.

**Comment by maxrd2** [comment]
There would be plans... If someone would write it lol :)
Have added #44 for that now.
Have planned to add proper documentation/examples on javascript/ruby/python scripting api and to add few HOWTO videos on site (which was WIP for some time now)
