### ISSUE TITLE
PocketSphinx plugin doesn't build on kubuntu

### ISSUE THREAD

**Issue by maxrd2** [maxrd2/subtitlecomposer#45]
When I install PocketSphinx dependencies I was unable to compile subtitlecomposer.

[make.log.zip](https://github.com/maxrd2/subtitlecomposer/files/195963/make.log.zip)

**Comment by maxrd2** [comment]
@muzena What version of pocketsphinx do you have installed?

**Comment by muzena** [comment]
This version:
https://launchpad.net/ubuntu/xenial/+source/pocketsphinx

**Comment by maxrd2** [comment]
It seems it's some older prealpha5 version than what is currently released.
Since both are says prealpha5 as version I can't make it work on both.
You'll have to patch the source in order to build it.

Didn't try to build it, but this should be enough:
[pocketsphinx-ubuntu-patch.txt](https://github.com/maxrd2/subtitlecomposer/files/196753/pocketsphinx-ubuntu-patch.txt)

**Comment by muzena** [comment]
@maxrd2 
Is this right source code?
https://github.com/cmusphinx/pocketsphinx
It is also 5prealpha.
If it is right source code, can i try compiled it and install on kubuntu?

**Comment by maxrd2** [comment]
yes.. that one is right.
It is also 5prealpha, but they have changed one function signature..
If you can apply patch I've posted to subtitlecomposer code, you should be fine with pocketsphinx version that you have installed already

**Comment by maxrd2** [comment]
Did you manage to solve this?

**Comment by muzena** [comment]
Yes this patch work but with additional build dependencies: libsphinxbase3 libsphinxbase-dev libpocketsphinx3, libpocketsphinx-dev and install dependencies: pocketsphinx, pocketsphinx-en-us.
Now is the problem with player plugins.
In Debian/Ubuntu/Mint they compile in /usr/lib/x86_64-linux-gnu/subtitlecomposer
instead in /usr/lib/subtitlecomposer
and why subtitle won't open any video file.
But this resolved this patch:
[fix-plugins-loading.diff.zip](https://github.com/maxrd2/subtitlecomposer/files/208400/fix-plugins-loading.diff.zip)

**Comment by muzena** [comment]
After your recent changes, i was unable to build Subtitlecomposer.
Build log:

[build.output.txt](https://github.com/maxrd2/subtitlecomposer/files/208975/build.output.txt)

**Comment by maxrd2** [comment]
Debian build files under pkg/ needs to be updated as they are pretty outdated.
Don't have debian system here so won't update them myself soon.
Regarding lib location please look into [configure](https://github.com/maxrd2/subtitlecomposer/blob/master/configure) and [install](https://github.com/maxrd2/subtitlecomposer/blob/master/install) files for proper invocation of cmake.

Am using following to prepare build on arch linux, I think similar/same should be fine for debian.
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DLIB_INSTALL_DIR=lib  -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DBUILD_TESTING=OFF
```

**Comment by maxrd2** [comment]
Have added better fix than that patch you've used for plugin loading.
It should load them properly now even if you use the debug build.

**Comment by muzena** [comment]
@maxrd2 
I try build again, I get same build error like before.

**Comment by maxrd2** [comment]
Have just tried building it on kubuntu 16 and have updated debian build files (there's a lot room for improvement).
It builds fine there.

LibMPV error you get is because of outdated libmpv.
You need some version that includes [this commit](https://github.com/mpv-player/mpv/commit/ef827af06cbf334a497fb0de8c9b75188549d03e#diff-1b826bcf1822b615bd1f8def6f0961b5) from Feb 2, 2015.

Please make sure you have latest versions of all dependencies installed if you get some more error messages.
I know some linux distros tend to keep old versions of some packages, while APIs of some libraries change over the years.

Will close this one now.

**Comment by muzena** [comment]
@maxrd2 
I think it's not outdated,  I look source libmpv code in ubuntu xenial it's updated 10 mart 23016
https://launchpad.net/ubuntu/+source/mpv/0.14.0-1build1

#define MPV_CLIENT_API_VERSION MPV_MAKE_VERSION(1, 20)

**Comment by maxrd2** [comment]
Function mpv_wait_async_requests() was added to libmpv on Feb 2, 2015 and it's still in there today.
If you don't have it in your mpv/client.h something is wrong, and my guess is that you have libmpv version using code released before that date.
BTW mpv/client.h in that package has mpv_wait_async_requests()

**Comment by maxrd2** [comment]
Please check that your /usr/include/mpv/client.h contains mpv_wait_async_requests(). If it doesn't something is wrong with your install. Try reinstalling that package. Remove any older libmpv headers that might by somewhere else in your include path.

**Comment by muzena** [comment]
There is no mpv_wait_async_requests() /usr/include/mpv/client.h
Then I download mpv source code from github and add debian pkg folder xenial mpv source code
but it won't compile I get some errors.
But when I compile mpv source code from ubuntu xenial It generates deb files but it's the same like from xenial repository without mpv_wait_async_requests().

**Comment by maxrd2** [comment]
That package in repository link you've provided above has client.h file that contains mpv_wait_async_requests()
So that one should work fine.

**Comment by maxrd2** [comment]
Your build log above shows:
```
-- Found MPV: /usr/lib/x86_64-linux-gnu/libmpv.so (version 1.13.0)
```
You must have two versions installed on your system and build is finding the wrong one.
Try executing following to find second version.. Did you build it manually and installed it under /usr/local ?
```
find /usr/ -name client.h -exec grep -Hn MPV_CLIENT_API_VERSION \{\} \;
```

**Comment by muzena** [comment]
Yes I know, I noticed this yesterday.
I didn't saw that I have installed old version of libmpv from trusty repository.
After removing repository and reinstalling libmpv compilation works.
