### ISSUE TITLE
Update waveform immediately after adding, deleting or editing a line

### ISSUE THREAD

**Issue by lunarrunner** [maxrd2/subtitlecomposer#46]
In V0.6.3, it seems like when I edit the text of a line, it is reflected in the waveform only when I hover the mouse over the waveform. When I add or delete one, I also have to scroll the waveform to see that change.

IMO, it would be better if all these changes could be shown immediately in the waveform.

**Comment by Martchus** [comment]
Works. Thanks for the fix.
