### ISSUE TITLE
Not all translated strings are displayed

### ISSUE THREAD

**Issue by Martchus** [maxrd2/subtitlecomposer#48]
As the title already says, not all translated strings are displayed. I only tested the German translation.

This problem might be caused by the way I edited the *.po file, so here is how I updated the translations:
1. I ensured that all required scripts are available by installing the Arch Linux package kde-dev-scripts
2. I entered the directory po
3. invoked ./Messages.sh
4. and edited the German *.po file with Qt 5 Linguist.

In 3. the sed line in the script messed up the permissions of all *.po files, so I used the workaround I already mentioned.

Almost all strings (including ones I added in the latest commits) are displayed correctly. Only a few are only displayed in English:
1. the strings in all settings pages except the spell checking page
2. the buttons in the scripts manager

**Comment by maxrd2** [comment]
Thanks for reporting this, have broken this some time ago when porting to KF5.
Should be all good now.

**Comment by Martchus** [comment]
Works. Thanks for the fix.
