### ISSUE TITLE
New command suggestion: repeat playback at currently selected line

### ISSUE THREAD

**Issue by lunarrunner** [maxrd2/subtitlecomposer#54]
My idea is similar to what you can find in Subtitle Edit: when you press a key (whatever is set in the keybindings) or press a button in the video controls, the video preview is played from the starting position of the current line until its ending position, and then it is paused immediately. (Whether the playback starts exactly where the line appears or several seconds before could be adjustable as well.)

Overall, such a command would be very useful for me because many times I need to listen certain parts more than once before I can come up with a proper translation/transcript.

**Comment by maxrd2** [comment]
Should be done
