### ISSUE TITLE
Waveform isn't displayed when opening Flash Video files

### ISSUE THREAD

**Issue by Martchus** [maxrd2/subtitlecomposer#56]
As the title already says, the waveform is not displayed when opening a file muxed using the Flash Video container (FLV). Video format is AVC and audio format AAC.

Both - audio and video - is played correctly with the gstreamer plugin. Only the waveform is missing.

When remuxing the file to Matroska or MP4 without converting the streams it works.

I already figured out the following information:
- StreamProcessor::initAudio returns true.
- g_signal_connect(fakesink, "handoff", G_CALLBACK(onAudioDataReady), this) within StreamProcessor::initAudio does *not* return 0.
- However, the callback function StreamProcessor::onAudioDataReady is never called.

I don't think this issue is important because Flash Video is a bad container format anyways. But sometimes I have such files and like to prepare the subtitles before muxing with a proper container.

**Comment by maxrd2** [comment]
Thanks for reporting it. Should be fixed with last commit.

**Comment by Martchus** [comment]
Thanks for fixing it. Haven't thought that this is actually checking whether a container is supposed to be supported before. Wouldn't it make more sense to just catch the error case if it turns out that a file is actually not supported by gstreamer?

**Comment by maxrd2** [comment]
That callback is used to decide which streams should be processed and which
should be ignored. And only way to differentiate between container and
video stream (that i know of) is by using mime type.

If i don't filter out not needed streams, stammer will connect decoders. In
case of video stream it will connect hardware decoders and everything, and
as result generating waveform becomes 10x slower, and it some cases it
breaks libav/vdpau decoding in main player widget.

So far this seemed like cleanest solution, but probably there is some
better way that i don't know of.

**Comment by maxrd2** [comment]
That callback is actually called whenever new source is added to gstreamer graph. And source is anything that supplies data that can be decoded by some gstreamer element. So for any container, video, audio, text or misc stream.
Possible solution would be to add some counter and always accept first found source, but should test if it would work properly in all cases.

**Comment by Martchus** [comment]
Sounds like a better approach. But this issue is fixed for now.
