### ISSUE TITLE
Mixed up numbering when inserting a new line after the last one on the waveform

### ISSUE THREAD

**Issue by lunarrunner** [maxrd2/subtitlecomposer#60]
When I right click on the waveform anywhere after the last line, let's say, number 5, and click on "Insert line", the numbering of these two lines are mixed up, so the newly inserted line becomes number 5 and the last but one becomes number 6.

Other than that, everything seems to work fine for me now.

**Comment by maxrd2** [comment]
Thanks, should be good now, was a bit hasty with last fix.
