### ISSUE TITLE
Splitting lines command does nothing

### ISSUE THREAD

**Issue by lunarrunner** [maxrd2/subtitlecomposer#65]
When I select Edit → Split Lines, nothing seems to happen even though the current position is in the middle of a long line.

Using the git version compiled on 25 June 2016.

Edit: I have the same result when I right click on a line in the list of lines and select Split Lines in the context menu.

**Comment by maxrd2** [comment]
That command splits a subtitle line into two or more, depending on how many newlines text has. Is the subtitle you're trying to split all written on single line?

**Comment by lunarrunner** [comment]
Oh… I understand now. Yes, the problem was that within a subtitle line all the text was written as a single line.

> Will change that command to split the line on the first whitespace in the middle of text. 

Also, checking if the subtitle line contains at least a new line character first would be nice, too, IMO. And if none is found, only then could it be splitted at a space in the middle.

**Comment by lunarrunner** [comment]
I've just tried it in the latest git version, and it splits both single and multiple lines nicely. Thank you very much!

**Comment by maxrd2** [comment]
Great...
Thanks for your feedback!
