### ISSUE TITLE
Play current line and pause command shouldn't select the next line

### ISSUE THREAD

**Issue by maxigaz** [maxrd2/subtitlecomposer#66]
Problem to reproduce:
1. Have 2 lines that are close to each other (e.g. there’s just a few ms gap between the two or the first one’s hiding time is exactly the same as the showing time of the second);
2. Turn on _Current Line Follows Video_;
3. Select the first line;
4. Use the _Play current line and pause_ command (I assigned a hotkey for it since I couldn’t find it in the menus or the toolbar);
5. When playback is paused, the second line is selected instead of the first one.

Even without step 2, it is still a nuisance when it comes to navigating with the keyboard, because when the first one is selected and that line has been repeated, Shift+Right jumps to the third line instead of the second.

**Comment by maxrd2** [comment]
This should work good now, would appreciate your feedback.

**Comment by maxigaz** [comment]
It is working now in the git version, indeed. Thank you very much!
