### ISSUE TITLE
Waveform widget cannot be scrolled when there is no audio

### ISSUE THREAD

**Issue by caryoscelus** [maxrd2/subtitlecomposer#68]
And so it becomes pretty useless - timing editing beyond first few seconds is impossible.

Loading video with sound track fixes the problem. It is still possible to scroll when soundless video is loaded back and old waveform is still present (however, no sound is played).

**Comment by maxrd2** [comment]
Have just opened video file with no audio tracks and it can be scrolled just fine.
Am I missing something?

**Comment by caryoscelus** [comment]
Hmm, i'm using version from Debian repos, so maybe it changed in master since that? I'll try latest version later and report then.

**Comment by maxrd2** [comment]
Have noticed that toolbar buttons are disabled without audio, but scrollbars and mouse scroll works fine.

**Comment by caryoscelus** [comment]
Yep, turns out that was an already fixed issue. However toolbar buttons are not fully fixed: when i open soundless video initially, zoom out button is disabled and zoom in gets disabled after a couple clicks. However, if soundless video is loaded after video with sound, they work good.

**Comment by maxrd2** [comment]
Are you sure you've checked out 159d2d8 ?
I can't reproduce it again :-/

**Comment by caryoscelus** [comment]
Yeah, double checked. It appears that zoom in button works fine (amount of times i'm able to click it depends on saved zoom level), but zoom out doesn't.

**Comment by maxrd2** [comment]
This should be ok now.. please reopen if not.

**Comment by caryoscelus** [comment]
Yeah, zoom buttons seem to work ok now. Thanks.
