### ISSUE TITLE
Printed text on video doesn't scale well with QT_SCALE_FACTOR enabled on high-dpi display

### ISSUE THREAD

**Issue by rubin110** [maxrd2/subtitlecomposer#69]
Debian Sid
KDE Plasma Desktop 5.8.4
Subtitle Composer 0.6.4-2+b1 

I have a ThinkPad X1 with a high-dpi display, and a 4k external monitor. I'm running KDE with a scale factor of 1.5 (this setting can be found in System Settings > Displays > Scale Display). This effectively sets QT_SCALE_FACTOR to 1.5 for the session. When I run Subtitle Composer, all of the printed on video text shows up pixelated and blocky (even with the anti-alias setting turned on). Currently I'm using Noto Sans as my go to font, however I'm able to reproduce this issue with pretty much every other font I've tested.

http://0.starset.net/screenies/20170225121222.png

If I scale back to 1, I have less of an issue (however everything on my screen is really small and hard to read), the pixelation isn't as pronounced...

http://0.starset.net/screenies/20170225122402.png

If you want to try this out without forcing the scale through the Display System Settings for your whole session, you can run something like this...

QT_SCALE_FACTOR=1.5 subtitlecomposer

You can find more about Qt and scaling here...

https://doc.qt.io/qt-5/highdpi.html

**Comment by Martchus** [comment]
Maybe all you need to do is `QCoreApplication::setAttribute(Qt::AA_UseHighDpiPixmaps, true)`.

**Comment by maxrd2** [comment]
@rubin110 Can you please check if this looks better now?

@Martchus Icons do look better with that, will include it soon... thanks

**Comment by rubin110** [comment]
I'm sorry. Is that an environment variable I should pass to the program or a compile option? If it's a compile options, do you have some documentation you can direct me to on how to build this? I'm currently running whatever package is in the Debian Did repo.

Thanks.

**Comment by Martchus** [comment]
@rubin110 I don't think that fix 6022856 needs any kind of activation. The attribute I proposed also won't (if included).

**Comment by rubin110** [comment]
Ah, ok I believe I understand now. Any guesses on when this might hit Debian or should I not hold my breath and just compile from source now?

**Comment by maxrd2** [comment]
Probably not before i tag a new version. If you could compile from sources and get me some feedback it would be really appreciated.

**Comment by rubin110** [comment]
Happy to. Do you have a doc or guide on how to compile this project? Thanks.

**Comment by Martchus** [comment]
The  files for packaging in the pkg dir contain build instructions and dependencies. Especially the Arch package should be easy to read.

**Comment by maxrd2** [comment]
As I said am not sure about debian packaging process, you can easily build and install it in your $HOME/subtitlecomposer/ (no need for root privileges) like this:
```
# install all build dependencies first (with dev packages): kcoreaddons sonnet kcodecs
# kross kxmlgui ki18n gstreamer cmake extra-cmake-modules
# if you want install optional dependecies: xine-lib mpv pocketsphinx
cd ~
mkdir subtitlecomposer
git clone https://github.com/maxrd2/subtitlecomposer.git subtitlecomposer-src
cd subtitlecomposer-src
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/subtitlecomposer -DLIB_INSTALL_DIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DBUILD_TESTING=OFF
make -j4
make install
# start the app with:
~/subtitlecomposer/bin/subtitlecomposer
```

**Comment by maxrd2** [comment]
Will close this now, feel free to re-open if there are more issues.
