### ISSUE TITLE
Question about pure Qt version

### ISSUE THREAD

**Issue by Katarn** [maxrd2/SubtitleComposer#71]
How much is the application tied to kdelibs? Is it hard to untie it from kdelibs, so that the application was written on pure Qt? It seems to me that this will have many advantages: it is easier to run on other platforms (especially considering that Subtitle Workshop has finally decayed), and more universal appearance under different working environments.

**Comment by Martchus** [comment]
I guess it would be possible to do everything also with plain Qt. However, it would be a lot of work. 

Note that since version 5 KDE frameworks are modular. So depending on a few KDE libs isn't a big deal anymore.

Which other platforms do you have in mind? If it is Windows, using the required KDE libs should be possible, too. There are already mingw-w64 packages in the AUR for all required libs except kross and kxmlgui.

Not sure why you think it would have a more universal appearance under different working environments. Subtitle composer looks and behaves like any other Qt Widgets application. It is possible to use any style and icon theme you want.

When creating other applications, I also decided to use plain Qt so I understand your concern. I just think it is not worth the effort to port the existing Subtitle Composer. Note that I'm not the maintainer of the project. Maybe he or somebody else is willing to do the porting effort.

**Comment by maxrd2** [comment]
From top of my head I can't think of any particular problems with moving away from kde libs.
Only problem is spending time to rewrite pieces of code that use kde classes, which is mainly main app class, main window, and open/save dialogs.

**Comment by Katarn** [comment]
@Martchus, I understand that there is a possibility to run under Windows now. I also know about the modularity of KDE5. However, in my opinion, this is not the program that requires a hard binding to the libraries of a certain desktop environment. In such cases, if some capabilities of a certain desktop environment are required, their support is added via options when compiling.

@maxrd2, thanks for the answer. If you will continue to develop the application, please write new components on a pure Qt, in order not to complicate the potential for a unbinding from the kdelibs.

**Comment by maxrd2** [comment]
Sorry, but I like it to be integrated with KDE desktop as much as possible.
I'm not using KDE classes for things that can be done in pure Qt with same result.

That said, I was also thinking some time ago on making SubtitleComposer KF5 dependencies optional, so it could compile easily on non-linux platforms. It doesn't seem like a lot of work after I went through porting the application to KF5.
If there are enough people interested in seeing and testing non-linux ports I might put some effort into it.

The most problematic thing I saw is having text codec selector in open/save dialogs, as Qt uses native file dialogs and doesn't allow of adding custom widgets in there, that will probably need different code for each platform.
Rest of the KF5 dependant code can be quite easily replaced or #ifdef-ed.

**Comment by Katarn** [comment]
As far as I understand, also need to rewrite the application settings window and keyboard shortcuts. Basically, if you ever decide to do this, I'll be ready to test for Linux and binary builds for Windows.

**Comment by shirishag75** [comment]
same here but only if there are debian builds.

**Comment by tosky** [comment]
Please note the one of goals of the kdelibs split into KDE Frameworks is also to provide a set of libraries that can be used by anyone on top of Qt.
The KDE Frameworks "product" is not a product related to a specific desktop or operating system, there are no kdelibs anymore.
The only connection with a desktop is the fact that the part of the KDE community also produces a desktop called Plasma, which uses the same libraries. But please consider that also lxqt makes uses of some of those libraries, thanks to the modularity.

All Frameworks libraries are working on different operating systems. Qt provides the isolation from the underlying environment, including the look&feel (for example in a Gtk+ environment, or Windows, etc).

In other word, removing the dependencies on Frameworks libraries will only lead to a reduction of functionalities for nothing, in the best case; or worse, duplicated code to reimplement a reduced version of the same functionalities, with a lot of ifdefs to maintain.

**Comment by Katarn** [comment]
@tosky, In theory, this is so. In practice, the complexity of the dependencies in the project still has a lot of problems. For example. I work in Xfce, I write on the Russian keyboard layout. Each opening the text search dialog resets the keyboard layout to English. In one day has to switch the keyboard layout back to Russian a few hundred times. Other example. I installed Krusader, but it completely lacks file copy dialogs. I just do not know the progress of copying. It turns out that I have to install almost full the KDE, so that I have a settings panel, just so that I can mark one checkbox there. Then I will see the progress of copying. The same settings panel I need to customize the look of KDE applications, by default its look horrible. It's only my configuration, but there are thousands and thousands of them. At first glance it seems that everyone has foreseen, but in fact... In programming, as nowhere is the need for the razor of Occam.

**Comment by tosky** [comment]
The example that you brings are not counterfact to what I wrote. Bugs exists, if we were to reimplement everything to not depend on other's bug everyone would have to rewrite openssl/gnutls, or readline, or X11 binding, or why not Qt or Gtk+?

The look and feel of Qt applications (there are no more special "KDE applications") depends only on Qt settings, and if your environment does not provide a way to set that (there is a native Gtk+ platform plugin in Qt), then you can use a generic one like qt5ct. Plasma (not KDE, which is only the name of desktop, and that's for a reason - KDE is the community) happens to ship with a control panel to control it too, but it's not something reserved to it or needed to use Qt applications.

**Comment by Katarn** [comment]
> The example that you brings are not counterfact to what I wrote.

Why not? I'm talking about a reasonable number of dependencies, first of all. Anybody does not argue, that in the Linux-ecosystem with many count of intermediate layers there are big problems. @maxrd2 said above that the application is almost entirely written on a pure Qt. It turns out that because of a couple of optional functions a relatively thick intermediate layer is used. This, excuse me, goes beyond reason. So you can say that Electron for a calculator is a good choice. "Just" one dependence with one executable file and one Blink-library. Good modularity and so on, nothing extra.

But I repeat, I do not propose to refuse from KDE Frameworks. I propose to make it possible to compile the application without dependence to it. All functions that relate to the KDE as a desktop environment are just use in configure-flags.

**Comment by tosky** [comment]
Frameworks is not an "intermediate layer" (which looks like a big blob): it's a collection of add-ons libraries for Qt. Nothing thick. A relevant number of them depends on Qt only. Electron is, on the other side, a big blob even if it's one, and I'm the last person on the earth who advocates its usage.

> All functions that relate to the KDE as a desktop environment are just use in configure-flags.
Frameworks is not a set of functions that related to Plasma. Plasma uses some Frameworks libraries in the same way that it uses Qt.
Frameworks is already the moduality that you need., I'd strongly suggest to recheck what  KDE is and what KDE does (the fact that you use "KDE" for the desktop may show some lack of updates in what KDE really does these days).

**Comment by tosky** [comment]
I'm suggesting that it's not worth to introduce ifdefs to remove few libraries for a supposed Qt "purity" (poor mudbloods). It's not just the opening/saving files adapted to the environment (which is already something that people looks for).

**Comment by Katarn** [comment]
Ok, I have some questions.

1. How to fix problem with keyboard layout?
2. How to compile app for Windows from sources? In case Qt I just install QtCreator.

**Comment by Martchus** [comment]
> How to fix problem with keyboard layout?

If the same ways as if the buggy code was part of subtitle composer itself: You have to fix the buggy code.

> How to compile app for Windows from sources? In case Qt I just install QtCreator.

You have to compile all dependencies of course. This is true for *all* dependencies of this application, regardless whether those dependencies are part of KDE frameworks.

**Comment by Katarn** [comment]
> If the same ways as if the buggy code was part of subtitle composer itself: You have to fix the buggy code.

The matter is that in source codes of Subtitle Composer I did not find something related with change of a keyboard layout. However, I see that the KFindDialog is used.

> You have to compile all dependencies of course. This is true for all dependencies of this application, regardless whether those dependencies are part of KDE frameworks.

When I compiled the KDE libraries into Gentoo, there were 100+ dependencies. I was saved only by the fact that the compilation scripts were written by the maintainers of distro. From this point of view, the compilation of SC under Windows seems to me an impossible task.

**Comment by Katarn** [comment]
> So you go ahead and find the bug there (or just open a ticket on the KDE bug tracker). Still, there's no difference between dependencies which are part of KDE libs and other dependencies. Eg. in case you encounter problems with the MPV backend, you might need to look into MPV's code.

Yes, but above I said that the less dependencies, then less bugs. :) And KDE Frameworks is just a huge field for errors. It's enough to remember the quality of the Plasma code. KDE Frameworks and Plasma - is one project although different libraries.

> I would use the mingw-w64 package from the AUR. I think only 3 packages would be missing there. If you like to compile it on Windows, there's also MSYS2. Besides, the number of required KDE libs is much smaller than 100.

Obviously, I compiled them almost from scratch (to be precise, the installation of KDE libraries required the updating of almost the rest of the system), just as they will have to compiled on Windows. This - libgif, libpng, openssl and many and many others in them dependences tree.

**Comment by Katarn** [comment]
@tosky, hmm, thanks, I'm try it a little later.

**Comment by smaragdus** [comment]
If someone manages to compile [Subtitle Composer](https://github.com/maxrd2/subtitlecomposer) for Windows I may test it. Currently [Subtitle Edit](https://github.com/SubtitleEdit/subtitleedit) (written in C# and requiring .NET) doesn't have so many alternatives under Windows as both [Aegisub](http://www.aegisub.org/) and [Subtitle Workshop](http://subworkshop.sourceforge.net/) seem to be abandoned.

**Comment by maxrd2** [comment]
Have uploaded win32 build and install here: https://github.com/maxrd2/SubtitleComposer/releases/tag/win32

Would appreciate some feedback on:
- It should have native look - if not have probably missed some Qt plugin
- Loading of various subtitle formats both text and image (vobsub, PGS, etc)
- MPV player plugin should work fine - please let me know if you encounter some video/dvd/bluray it doesn't want to open
- Waveform should render fine - otherwise let me know please
- GStreamer player backend is not working - if it's working for you please let me know :)
- MPlayer backend - should work if you install mplayer.exe somewhere and configure path - please let me know

TODO:
- Subtitle open/save dialogs should be reworked - issue #115
- Speech recognition is not compiled in yet, if someone wants to make mingw-w64 pocketsphinx/sphinxbase PKGBUILDs please make a pull request here: https://github.com/maxrd2/arch-repo
- Spell checking plugins are not included yet
- Something else?

**Comment by Katarn** [comment]
Thank you!
