### ISSUE TITLE
mpv work not properly

### ISSUE THREAD

**Issue by alium** [maxrd2/subtitlecomposer#73]
If you use MPV as backhand, with newest version of mpv (0.24.0) show new window if you open subtitle with text: 
--softvol=no is not supported anymore. 

Sound only, no video.

**Comment by alium** [comment]
Log:
see ===>> [MPV: cplayer ]  warn :  --vo=opengl-hq is deprecated! Use --profile=opengl-hq instead.
[MPV: lavf ]  info :  Using subtitle charset: ISO-8859-2
[MPV: cplayer ]  info :   (+) Video --vid=1 (*) (h264)
[MPV: cplayer ]  info :   (+) Audio --aid=1 --alang=eng (*) (aac)
[MPV: cplayer ]  info :       Subs  --sid=1 'The.Founder.2016.1080p.BluRay.X264-Goody.to.srt' (subrip) (external)
[MPV: display-tags ]  info :  File tags:
[MPV: display-tags ]  info :   Title: 2The Founder 2016 1080p BluRay X264 goody to
Generated caps:  audio/x-raw, format=(string)U8, width=(int)8, depth=(int)8, signed=(boolean)false, rate=(int)8000
[MPV: cplayer ]  info :  AO: [pulse] 48000Hz 5.1 6ch float
see ===>> [MPV: cplayer ]  error :  --softvol=no is not supported anymore.
Error loading text-to-speech plug-in "speechd"
Selected audio stream # 0  [ src_1 ]  audio/x-raw, format=(string)F32LE, layout=(string)interleaved, rate=(int)48000, channels=(int)6, channel-mask=(bitmask)0x000000000000003f
org.kde.knotifications: Audio notification requested, but sound file from notifyrc file was not found, aborting audio notification
[MPV: vd ]  info :  Using hardware decoding (vaapi).
[MPV: cplayer ]  info :  VO: [opengl] 1920x800 vaapi[nv12]

**Comment by maxrd2** [comment]
Strange, I'm also using MPV backend all the time and it worked fine here with version 0.24, and now 0.25.
Can you please try to give me more precise steps to reproduce this?

**Comment by mockroot** [comment]
Strange. I had the same problem last week. Now I tried again to give you details, it worked properly. (mpv 0.25 - under archlinux)

**Comment by alium** [comment]
I make all steps as @mockroot  suggest -> i set  as video output driver 'opengl-hq'  and HW decoding 'vaapi', i can't  see video,  audio only :-(

But if i set vaapi + vaapi, all works ok. But normally i should use (and i use) --profile=opengl(-hq) instead vaapi.

-------
from https://github.com/mpv-player/mpv/blob/master/DOCS/man/vo.rst:

Opengl: 
By default, it tries to use fast and fail-safe settings. Use the opengl-hq profile to use this driver with defaults set to high quality rendering. (This profile is also the replacement for --vo=opengl-hq.) The profile can be applied with --profile=opengl-hq and its contents can be viewed with --show-profile=opengl-hq.

vaapi:
Intel VA API video output driver with support for hardware decoding. Note that there is absolutely no reason to use this, other than compatibility. This is low quality, and has issues with OSD.

**Comment by alium** [comment]
I finded the problem! The problem causes really the opened window with the 'softvol' error!
I changed in mpvbackend.cpp 'softvol' to 'volume':

	if(SCConfig::mpvVolumeAmplificationEnabled()) {
		mpv_set_option_string(m_mpv, "volume", "yes");
		mpv_set_option_string(m_mpv, "volume-max", QString::number(SCConfig::mpvVolumeAmplification()).toUtf8().constData());
	} else {
		mpv_set_option_string(m_mpv, "volume", "no");

and after recompiling subtitlecomposer works and play video with video output driver 'opengl-hq' again!!!

**Comment by Martchus** [comment]
@alium Make a PR :-)

**Comment by alium** [comment]
@Martchus 

created... :-)

**Comment by maxrd2** [comment]
@mockroot thanks have fixed softvol and updated vo device list
@alium thanks for pr, can you please check if last commit i've pushed works for you?

**Comment by alium** [comment]
last commit tested and works perfect:

> [MPV: vd ]  info :  Using hardware decoding (vaapi).
>[MPV: cplayer ]  info :  VO: [opengl] 1920x804 vaapi[nv12]

**Comment by alium** [comment]
fixed for me :-)
