### ISSUE TITLE
Create and distribute Ubuntu Snap package with SubtitleComposer

### ISSUE THREAD

**Issue by luzfcb** [maxrd2/subtitlecomposer#75]
Recently, I've done some experiments with the goal of building a snap package of subtitlecomposer.
[Snap package](https://www.ubuntu.com/desktop/snappy) is interesting because it works in isolation from the rest of the system, like a docker container.

This allows you to distribute subtitlecomposer with all execution dependencies, and because it works in isolate environment, you can also send some specific version of QT, KF5 and other.

I created the basic files to generate a snap package from the subtitlecomposer source code: https://github.com/luzfcb/subtitlecomposer-snap

It can generate the snap package, and run subtitlecomposer as snap app.

However, not everything is working perfectly yet. For example:
* the dialog box to open the subtitles does not show any files, but the dialog to open video show. I believe this has to do with some misconfiguration of the KF5 and / or QT environment variables.
* I have not yet been able to make snapcraft create subtitlecomposer snap app launcher icon on user menu

Another thing I am not very happy, because Ubuntu 16.04 has old versions of KF5 and QT, and due to this, I was forced to use "KDE Neon user LTS" as compile environment (KDE Neon is distribution based on Ubuntu 16.04 with the latest versions of KDE and Plasma, created directly by the KDE project). This resulted in a base docker image, required to compile snap, with more than 3GB. 

To solve this, I thought of compiling QT5.8, KDE Framework 5.33 and pocketsphinx directly from the source code. So I can have more control of snap package compile environment and I can create a smaller docker image, only with the specific dependencies of subtitlecomposer.

I am having difficulties in how to configure cmake for it to use another directory different from the system to find QT, KDE Framework, pocketsphinx and sphinxbase. Could you teach me how to do this?

If you want to test the snap package that I created, download this file[1] and run this command to install

```bash
sudo snap install --dangerous --devmode subtitlecomposer_0.6.4+git_amd64.snap
```
to run:

```bash
snap run subtitlecomposer
```

[1] subtitlecomposer_0.6.4+git_amd64.snap: https://drive.google.com/open?id=0B0qPRYTwNJrfaW1lQTJ4aXdTS3M

**Comment by Martchus** [comment]
> I am having difficulties in how to configure cmake for it to use another directory different from the system to find QT, KDE Framework, pocketsphinx and sphinxbase. Could you teach me how to do this?

Did you already try to set `CMAKE_MODULE_PATH`?

**Comment by luzfcb** [comment]
I'm using these instructions to compile:

https://github.com/maxrd2/subtitlecomposer/issues/69#issuecomment-287506325

ps: I still do not understand completely how cmake works, since I am not a C++ programmer and this is one of the few times I needed to compile C++ directly from the source code. It's been an interesting experience :-).

**Comment by maxrd2** [comment]
Please try looking at [step 4 here](https://github.com/maxrd2/subtitlecomposer/wiki/Building-from-sources).. Think that should solve building with Qt/KDE in non-standard location.
