### ISSUE TITLE
Changes in "Quick Actions" are not applied.

### ISSUE THREAD

**Issue by luzfcb** [maxrd2/subtitlecomposer#78]
Changes in "Quick Actions" are not applied.

The button "Apply" only enable if i make changes in "General", however, even the changes in Quick Action are not persisted and are lost after closing the configuration window;

I compiled subtitlecomposer from source (commit https://github.com/maxrd2/subtitlecomposer/commit/673be69921a8730afbe7dfd18ed9b0b3ca3ae8b4 )

![image](https://cloud.githubusercontent.com/assets/807599/25879319/6285d5a4-3507-11e7-9041-cc2b1f4a481c.png)

ps: from the image: the values I need to use are correct, I need to set 1 ms for everything.
In my current job, I need to watch several video lessons and mark the points of the video that i think they need to become a chapter. subtitlecomposer is helping me a lot in this work. Thanks for your hard work in creating this beautiful piece of software.

**Comment by maxrd2** [comment]
Should be fixed now :)
