### ISSUE TITLE
Hide time should not be less than show time

### ISSUE THREAD

**Issue by luzfcb** [maxrd2/subtitlecomposer#79]
In addition to generating a subtitles file with invalid time data, this causes a side effect, while there is this error, you can not edit the time of the a subtitle on the Waveform panel

![image](https://cloud.githubusercontent.com/assets/807599/25978396/29a2f77a-3698-11e7-9ff5-bcf522e8dd44.png)

**Comment by maxrd2** [comment]
Thanks for report, should have fixed all cases in which this was possible to do.
Feel free to reopen if there are still problems.
