### ISSUE TITLE
Segmentation faults under Arch Linux

### ISSUE THREAD

**Issue by Martchus** [maxrd2/subtitlecomposer#80]
### Observation
It seems that latest updates of Qt/KDE libs under Arch Linux causing segmentation faults when starting Subtitle Composer. Concerning line is 219 in `application.cpp`. The backtrace is quite long and goes down to some internals of `dl_open` which is called inside the XCB Qt platform abstraction plugin.

Interestingly, when showing a QMessageBox before `app.init()` the application starts and works as expected. However, when closing it again a segmentation fault occurs in the destructor of `SimpleRichTextEdit::~SimpleRichTextEdit()` when closing the application.

When using the debugger to step into `app.init()` I get the following output:
```
can't find linker symbol for virtual table for `SubtitleComposer::UserActionManager' value
  found `QtPrivate::MetaTypeSmartPointerHelper<QAbstractItemModel*, void>::registerConverter(int)' instead
```

Sometimes I've also got warnings about missing RTTI info of some Qt classes.

So something is definitely messed up in subtitle composer, no other KDE apps have similar problems.

### Steps to reproduce
Just build subtitle composer (preferably debug build) under current Arch Linux (Qt 5.9.0, KDE 5.35) and try to start.

### Workaround
Show some dialog before `app.init()`.

---

I have already tried to figure out what's going on but still have no clue. I'll try to further investigate this, but maybe you can help.

**Comment by maxrd2** [comment]
I can't reproduce this at all on latest arch install. Did you try deleting completely build directory and calling cmake/make after that? From the error it seems that build directory has some corrupt/incompatible objects.

**Comment by Martchus** [comment]
Yes, I cleaned the build directory completely.

Also the packages I provide in my repo don't work for me.

* https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/subtitlecomposer-0.6.4-4-x86_64.pkg.tar.xz worked for me at the time I built it but now it fails to start
* Same for the git version: https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/subtitlecomposer-git-344.5c80dde-1-x86_64.pkg.tar.xz.
* Already tried to rebuild it but the package (in clean and current chroot) but resulting package doesn't work, too: https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/subtitlecomposer-git-344.5c80dde-2-x86_64.pkg.tar.xz

**Comment by Martchus** [comment]
I've just tried to run subtitle composer on my server which is also up-to-date and using the same package which doesn't work here and it runs fine. 

So maybe there is something wrong on my workstation. Or the error only occurs under special circumstances.

**Comment by maxrd2** [comment]
Did you manage to figure something else here?

**Comment by Martchus** [comment]
No and the issue still persists. I'm going to further investigate this.

**Comment by Martchus** [comment]
The problem was caused by the package `atlas-lapack-base` from the AUR which still installed on my workstation but required a rebuild against new `libgfortran`.

However, the package has been replaced by official packages so `atlas-lapack-base` is not required anymore anyways. In case someone ran into the same issue, the following command fixes it: 
```
sudo pacman -S lapack blas cblas
```
