### ISSUE TITLE
KFileDialog does not show webm file

### ISSUE THREAD

**Issue by ShalokShalom** [maxrd2/subtitlecomposer#81]
I rendered a webm file with VP8 in Kdenlive and tried to open that one with SubtitleComposer.
It is possible, while i need to set the filter in the file dialog to "All Files" since it does not get detected as Media File and Video File.

**Comment by JacquesDuflos** [comment]
Yes, same remark for .divx files

**Comment by maxrd2** [comment]
should be fixed.. thanks

**Comment by RedSoxFan04** [comment]
I'm still experiencing this problem.

**Comment by ShalokShalom** [comment]
Which version?

**Comment by RedSoxFan04** [comment]
The latest version in the Debian Buster repositories - 0.6.5

**Comment by ShalokShalom** [comment]
Well, it seems my version allows currently no other option as "All Data" and it works.
Maybe a packaging issue? You can write a mail to pkg-kde-extras@lists.alioth.debian.org

**Comment by maxrd2** [comment]
@RedSoxFan04 That should be fixed now too.
