### ISSUE TITLE
Add "Open Video" to the File menu

### ISSUE THREAD

**Issue by ShalokShalom** [maxrd2/subtitlecomposer#82]
I suggest to add the entry "Add Video" (also) into the file menu or the toolbar, since i just tried to add such one via the "Open" entry, which happens for sure nearly everybody, who is new to the project.

**Comment by maxrd2** [comment]
I'm not sure, it kind of make sense to me to have everything video related under Video menu.
Would like to hear what other (new) users think about it before changing it.

**Comment by ShalokShalom** [comment]
I dont recommend to change it in that way. Of course, it makes sense to keep it in the video category (as well) I suggest to place it more popular. Maybe move the video category more to the left? Next to `File`?

**Comment by ShalokShalom** [comment]
Other options would be to keep it in the Video and the File tab, or place it in the toolbar. While, i think i like the "Video next to File" option most.

**Comment by ShalokShalom** [comment]
What do you say to this?

**Comment by Martchus** [comment]
After `File` usually comes `Edit` (if present). I would not change this.

But in fact, I searched for opening a video file also under `File` in the first place. Not sure whether moving around top level actions is very helpful.

Maybe:
```
File
 -> New
 -> Open subtitle file ...
 -> Recently opened subtitle files
 -> Open video file ...
 -> Recently opened video files
...
```

So the suggestion is to keep the `Video` action where it is and how it is. Instead the the first and the second child action of the `Video` action are also displayed under `File`. That the functions can then be accessed using different actions is not a problem IMO - the toolbar already uses the same concept.

**Comment by ShalokShalom** [comment]
I agree.

**Comment by maxrd2** [comment]
Have moved open video entries to File menu in the end. It probably has most sense like that.
After upgrading, you might need to delete ~/.local/share/kxmlgui5/subtitlecomposer/subtitlecomposerui.rc file to actually see the change.

Thanks for feedback guys
