### ISSUE TITLE
Cant use more than 100% volume 

### ISSUE THREAD

**Issue by ShalokShalom** [maxrd2/subtitlecomposer#83]
plasma-pa offers the option to increase the volume over 100%

SubtitleComposer refuse to accept this. All new versions. (KaOS rolling)

**Comment by maxrd2** [comment]
I can't reproduce this, it works fine here. Which video player backend do you use?

**Comment by ShalokShalom** [comment]
Gstreamer and Phonon. 

I use all the newest, kf5 5.36 and Qt 5.9 etc, you?

**Comment by maxrd2** [comment]
I think i figured what you mean.
plasma-pa allows you to increase volume over 100%, but you can't increase it over 100% from within subtitlecomposer?
It works fine if you increase it to 150% from plasma-pa.. correct?

**Comment by ShalokShalom** [comment]
nope, Subtitlecomposer refuse to accept the plasma-pa setting. It resets back.

**Comment by maxrd2** [comment]
Strange.. i was able to increase it to 150% from outside subtitlecomposer with all backends.
Have just pushed improvement to gstreamer backend, you should be able to go >100% from subtitle composer now. Can you please try if that fixes it?

**Comment by ShalokShalom** [comment]
Can you make a new release? Together with the "file format not recognised fix" is it worth.
And my maintainer more likely to update it for all. 

My build fails with make: *** No rule to make target 'composer/pkg/subtitlecomposer'.  Stop.

**Comment by maxrd2** [comment]
Are you following instructions here?
https://github.com/maxrd2/subtitlecomposer/wiki/Building-from-sources

Can you attach complete build output please.
Will tag new version soon, once all fixes are confirmed.

**Comment by ShalokShalom** [comment]
I simply adopted the PKGBUILD of m distro: https://gist.github.com/ShalokShalom/0a79930925ab294f364a5d5b7195095e

It fails at line 30, while it builds fine with the release 0.6.4

**Comment by maxrd2** [comment]
Builds fine with your PKGBUILD here.
I can't help you if you don't provide detailed build output.

**Comment by maxrd2** [comment]
Release 0.6.5 has been tagged.
Also git version has cmake build script cleaned up a little.

**Comment by ShalokShalom** [comment]
A use the new release now and when the volume is at 150% and I reduce it in subtitle composer itself jumps it down to 100% regardless how tiny my change is. 

Same when I stop the playback and same when I pause and resume the playback.

**Comment by maxrd2** [comment]
I can't reproduce any of these issues with subtitlecomposer's **gstreamer** backend.
Are you sure you are using gstreamer backend and not something else?

**Comment by ShalokShalom** [comment]
![screenshot_20170923_105453](https://user-images.githubusercontent.com/6344099/30771675-a3fc9a5c-a04d-11e7-9e25-86948343aeee.png)

**Comment by maxrd2** [comment]
you are using Phonon backend in subtitle composer... please go to settings and change player backend to gstreamer (which should be default)

**Comment by ShalokShalom** [comment]
Yep, works now. Phonon is default here in this setting. I will forward this to our maintainer. Thanks a lot
