### ISSUE TITLE
Add option to "Insert now"

### ISSUE THREAD

**Issue by ShalokShalom** [maxrd2/subtitlecomposer#84]
I like to create a button, which insert a line on the current state of the player

**Comment by maxrd2** [comment]
You can do that by right-clicking/right-dragging on the waveform widget.
There are also Insert Before/After actions which will add lines before currently selected subtitle. There is also an option to enable so currently selected line follows video.

**Comment by ShalokShalom** [comment]
Yes, the thing is that casual users search this feature in the top menu and the toolbar. Nobody would look for it there, especially new users fail to create a line than. And this is a key, essential thing to do.
