### ISSUE TITLE
Python and Ruby scripts dont work

### ISSUE THREAD

**Issue by JacquesDuflos** [maxrd2/subtitlecomposer#85]
When trying to run the examples of scripts, python and ruby show the messagebox "Failed to determine interpreter for scriptfile <compleat/path/to/python/script.py>".
The first line of the python file 
`#!/usr/bin/env python`
is supposed to prevent that, but for some reason it does not.

**Comment by maxrd2** [comment]
Not sure which distro you are using, but it seems to me you are missing "kross-interpreters" or similar package. It should provide following files:
```
/usr/lib/qt/plugins/krosspython.so
/usr/lib/qt/plugins/krossruby.so
```

**Comment by maxrd2** [comment]
Will close this one now, feel free to re-open if you have more problems with executing scripts.
