### ISSUE TITLE
Option of not using video at all is not available. 

### ISSUE THREAD

**Issue by shirishag75** [maxrd2/subtitlecomposer#86]
Thank you for maintaining subtitlecomposer.  I have been using it for quite a while. I am using subtitlecomposer 0.6.4 which hasn't seen a new release since last year although have seen there is activity in form of commits,  https://github.com/maxrd2/subtitlecomposer/commits/master .  Hopefully there will be a new release soonish. 

Anyways, many a times when working with subtitles, I find it difficult to work with video, it is distracting and takes quite a bit of computing resources, however which video backend I use. In the last version in Subtitle composer > Settings > Configure Subtitle Composer there isn't a way to uncheck video, if possible please add/introduce it in the next version please.

**Comment by maxrd2** [comment]
There is an option on Settings > Configure Subtitle Composer > General tab labeled "Automatically load video file when opening a subtitle"
If you uncheck that one, videos will not autoload/play when opening subtitle file.
Is this what you need?

Version 0.7 will be released soon, am finishing/testing some new features and have some more fixes to complete before tagging it.

**Comment by Martchus** [comment]
> Hopefully there will be a new release soonish.

Note that at least for Arch Linux there exists a Git package. This should be possible for other distros, too. So there is no need to rush a new release in my opinion.

**Comment by shirishag75** [comment]
Ah thanx,  that fixed it.
