### ISSUE TITLE
No colored icons

### ISSUE THREAD

**Issue by duck7000** [maxrd2/subtitlecomposer#91]
Hi 

I'm testing Manjaro linux and probably will make the switch because it is a rolling distro and the software is much newer than Linux mint. And i like it!

But i have a question
In my other post about compile errors on Linux mint i'm using the pre-built version made by Muzena and it works great on Linux mint. It also has colored icons in the toolbar and file menu that looks to me from gnome?
On Manjaro i use the AUR repo and installed the latest git version (i think it is maintained by maxrd2?) but when i start the program there are no colored icons like on Linux mint, only gray icons who are different than Linux mint.
Is this a program or Manjaro issue? Or is this normal behaviour?

If i start subtitle composer on the terminal than there are a lot of errors:
vibrancy icons not found in multiple locations
ubuntu-mono-dark icon theme not found
qt5ct: D-bus global menu: no

On exit there is one  more error:
QCoreApplication::postEvent: Unexpected null receiver,. (This is obviously not related to icons i think)

Can this be of any help?

**Comment by Martchus** [comment]
The appearance of the icons depends on the icon theme which is used. The icon theme is configured on GUI-toolkit level. Subtitlecomposer is based on Qt 5, so you have to look up (eg. in the Arch Wiki) how to tell Qt 5 applications which icon theme to use. Hint: the Qt 5 platform plugin (seems like you're using qt5ct) can control such settings.

**Comment by duck7000** [comment]
Thank you very much, it works!

I didn't know that the icons of qt programs can be switched independently from system theme.

is the error on exit important?
QCoreApplication::postEvent: Unexpected null receiver,.

**Comment by maxrd2** [comment]
You can see info on those error messages in issue #87 
Will close this one now.
