### ISSUE TITLE
Documentation on Debian / Ubuntu?

### ISSUE THREAD

**Issue by fuxoft** [maxrd2/subtitlecomposer#94]
I use SC in Xubuntu and when I try to open "Subtitle Composer Handbook", I get a khelpcenter window saying that documentation was not found. I understand you cannot be responsible for .deb packages but I'd like to access the documentation in any possible way, download it manually or even browse it online. However, I cannot even find the docs here on Github. Where should I look to find SC documentation (in any format)?

**Comment by maxrd2** [comment]
At the moment there is no documentation. It is planned though, there is already an issue from some time ago #44
