### ISSUE TITLE
Possible to advance exactly one frame forward / backward?

### ISSUE THREAD

**Issue by fuxoft** [maxrd2/subtitlecomposer#95]
Is there a keyboard shortcut or UI button to advance exactly one video frame forward / backward?I sometimes need to exactly match the subtitle endings to video cuts and I work with various FPS (30, 24, 25...).

**Comment by maxrd2** [comment]
Will look into adding it. It's not trivial change as all player backends should be changed.

**Comment by fuxoft** [comment]
Thanks. Is there currently way to do it using a script?

Alternatively, is there a way to have two different sets of shortcuts for short jump and long jump? I normally use +/- 2 seconds jump but occassionally have to navigate by very small intervals (ideally 1 frame).

**Comment by maxrd2** [comment]
This should be done. It works only with MPV and GStreamer player backends.
Number of frames to step is configurable from player settings.
Seems that GStreamer for some reason doesn't support seeking by number of frames, so it's not very precise/fast. MPV implementation works better.

**Comment by maxrd2** [comment]
Will close this for now, feel free to reopen it.
