### ISSUE TITLE
Use Qt's Undo Framework

### ISSUE THREAD

**Issue by SafaAlfulaij** [maxrd2/subtitlecomposer#97]
I was translating the application into Arabic and found many strings that can't be found in the UI.
By digging a bit I found this in `application.cpp`:
```
void
Application::updateUndoRedoToolTips()
{
	static QAction *undoAction = action(ACT_UNDO);
	static QAction *redoAction = action(ACT_REDO);

	static const QString undoToolTip = undoAction->toolTip();
	static const QString redoToolTip = redoAction->toolTip();

	if(m_subtitle) {
		if(m_subtitle->actionManager().hasUndo())
			undoAction->setToolTip(undoToolTip % QStringLiteral(": ") % m_subtitle->actionManager().undoDescription());
		else
			undoAction->setToolTip(undoToolTip);

		if(m_subtitle->actionManager().hasRedo())
			redoAction->setToolTip(redoToolTip % QStringLiteral(": ") % m_subtitle->actionManager().redoDescription());
		else
			redoAction->setToolTip(redoToolTip);
	}
}
```

Can we not reinvent the wheel and just simply use [the proper way](http://doc.qt.io/qt-5/qundo.html)? This makes it easier in development and provides us translators some useful info.
Check: 
- http://markmail.org/message/y74nf42ntpyvb3su
- https://phabricator.kde.org/D9096
- http://doc.qt.io/qt-5/qundocommand.html#setText

**Comment by maxrd2** [comment]
Thanks for reporting this. That code has been probably lying around for long time.
Will look into improving it asap.

**Comment by maxrd2** [comment]
Replaced with qt's undo framework.
