### ISSUE TITLE
Make VobSub workable for non-latin languages

### ISSUE THREAD

**Issue by SafaAlfulaij** [maxrd2/SubtitleComposer#98]
In some languages, like Arabic, i's impossible to use the "symbol" was to identify the letters, since many letters have different dots but identical in the "base" shape.

Check the letters 2-4, 5-7, 8&9, 10&11, 12&13, 14&15, 16&17 and 18&19 (from right), they are exactly the same but with different dots.
![Arabic alphabit](http://1.bp.blogspot.com/-F3XM_9VOvag/T8Y1J8diiAI/AAAAAAAAAGI/pD_xygYLoxo/s1600/arabic+alphabets.bmp)

Yes, you can't read Arabic, but you can notice the similarities in "base" shapes between letters ;)

I think if we add an option to add all the lines with empty content to the subtitle, and let the user enter the whole line by displaying it in the video widget (alone, or in a special mode), that will solve this issue.
Or, make it possible that the user selects multi-symbols and add the letter that defines them. Then the app will search for these multi-symbols as a whole.

**Comment by maxrd2** [comment]
Am not sure I understand the problem. There is possibility to select multiple symbols for a single letter, and go back to previously detected letters and fix them. I have tested this with latin/slavic accented characters.

For example let's say there are these characters in subtitle in this order: àcaćäčá
à - here just letter below accent would get selected so you would have to change "Symbols" input value to 2 so both accent and a letter below get selected, then type 'à' in input box and press enter
c -here you would just enter 'c' and press enter
a - here you would just enter 'a' and press enter
ć - here letter 'c' would get autodetected and you would be asked about accent above - you have to click "< Prev Symbol" to select letter, then increase "Symbols" to 2, type 'ć' and proceed
ä, č, á - here probably same would happen as with 'ć' so you would repeat the steps

Doing that is a bit tedious, but after you define each letter correctly first time, the system should detect the correctly afterwards. It searches for most complicated letters first (most symbols) so when it encounters 'ć' and it was already defined with two symbols it will never mistake it for 'c'.

If this is not working like this for you please send me vobsub somehow and will look into fixing/improving it.

**Comment by Martchus** [comment]
When I've read this, I was also wondering what's the difference between such Arabic letters and accented characters.

**Comment by SafaAlfulaij** [comment]
Wow, thanks for the detailed explanation! :)
I've tried that and it did work to some extend, but not entirely.
Since it reads symbols from left to right, it reverse the symbol order for RTL lines.

Something like this (assume it is RTL and each word is a symbol):
TSET OT TAHW
in the dialog

will appear
TAHW OT TSET
in the subtitle list widget.

Of course this is just to explain, it's a bit more complicated since there are words that are made from 3 symbols or more. I don't want you to think that you can just reverse the order by the space letter. :)

@Martchus well, these are normal letters, but with different dots. We have something like accented characters that are [diacritics](https://en.wikipedia.org/wiki/Arabic_diacritics), but those are separate characters and not a part of the symbol, so not a problem at all.

**Comment by maxrd2** [comment]
Would be enough if dialog was start detecting text from right to left? I can add checkbox to enable RTL before vobsub rip starts.
Are there cases where RTL and LTR is mixed? I suppose not?

**Comment by SafaAlfulaij** [comment]
I think that would be enough. Mixing RTL and LTR is possible, but I think we don't need to go this deep if it will complicates the work.

**Comment by maxrd2** [comment]
@SafaAlfulaij Sorry that this took so long to implement. Was reading how RTL text is structured then got sidetracked with other things and it slipped my mind.

Have added some initial support per our conversation in commit b1d7a690c3b84992b064268bbdfb3d40bf2b2ca6 (rtl branch).

Should the code insert [RTL unicode mark](https://www.wikiwand.com/en/Right-to-left_mark) in text?

Could you please try that version and let me know if it's good?
AppImage can be downloaded from [here](https://github.com/maxrd2/subtitlecomposer/releases/download/testing-rtl/Subtitle_Composer-x86_64.AppImage) (releases page).

**Comment by SafaAlfulaij** [comment]
Thanks a lot! I don't have a Linux setup near me right now, but will test it this week!
Appreciated! :)

**Comment by maxrd2** [comment]
Issue was moved here: https://invent.kde.org/kde/subtitlecomposer/issues/10
