### ISSUE TITLE
How to make the spellcheck working?

### ISSUE THREAD

**Issue by duck7000** [maxrd2/subtitlecomposer#99]
Like the title, how does the spellcheck work in this program?

If i go to settings/spellcheck i get a error message: No backend found for spell checking?

I can only select default english, but i want dutch spell check

**Comment by duck7000** [comment]
I found out that i was missing a dependency:
Sonnet-plugins was missing
After i install this it works and i can choose dutch as spellcheck language.

Maybe this is something to mention by the install instructions or manual?

**Comment by maxrd2** [comment]
I think that is something that package maintainers should handle, as each distro has things packaged differently.

**Comment by duck7000** [comment]
I agree that it is up to the maintainer.

So this can be closed, Ubuntu 18.04 is just around the corner and later Linuxmint 19. It will include version 0.6.6 as far as i know so best for me is to have patience.

Keep up this excellent program!
